using System;
using System.Collections.Generic;
using System.Text;

namespace RIS.DataAccess
{
    public class StoredProcedure
    {
        public enum Name
        {
            Prc_LookUp_Age_Select,
            Prc_LookUp_RadiologistConfig_Select,
            Prc_LookUp_OPNoteHN_Select,
            Prc_LookUp_ExamOPNote_Select,
            Prc_LookUp_RIS_RADSTUDYGROUP_Select,
            Prc_LookUp_ResultLock_Select,

            Prc_LookUp_HeaderReport_Select,
            Prc_RIS_Rpt_Summary_Schedule,
            Prc_RIS_Rpt_Summary_ResultSpecialClinic,
            Prc_RIS_Rpt_Summary_Order,

          GBL_SESSION_VIEWER_UPDATE,
            GBL_SESSION_VIEWER,

            Prc_RIS_AUTOMERGECONFIG_INSERT,
            Prc_RIS_AutoMergeConfig_Select,
            RIS_AutoMergeConfig_Update,
            Prc_RIS_AUTOMERGECONFIG_DELETE,

            Prc_FormObject_Label,
            AlertObjects_Select,
            Prc_CreateNewSession,
            Prc_CloseSession,
            Prc_ShowAlert,
            Prc_GBLLookup,
            Prc_GBLExceptionLog,
            Prc_GBLProduct,
            Prc_GBLEnv,
            Prc_GBLMyFavourite,
            Prc_GBLUserMenu,
            Prc_GBLUserSubMenu,
            Prc_MyMenu_Insert,
            Prc_MyMenu_Update,
            Prc_SetFormAccess,
            Prc_PatientReg,
            Prc_Template_Insert,
            Prc_Addendum_Insert,
            Prc_ExamResult_Insert,
            Prc_ExamResult_Update,
            Prc_RadiologistAuthLevel,
            Prc_HL7Monitoring,
            Prc_ResultStatusChange,
            Prc_ResultStatusChangeLog,
            Prc_ResultEntryWorklist,
            Prc_ResultEntryHistory,
            Prc_SessionLog_IN_OUT,
            Prc_CheckSession,
            Prc_Modality_Load,
            Prc_DistributionChannel,
            Prc_CheckExamResult,
            Prc_ExamResultFor_Insert,
            Prc_ExamResultFor_Update,
            Prc_OrderImages_Insert,
            Prc_ReportExamResult,
            Prc_RIS_SCHEDULE_REPORT,
            Prc_EmployeeScheduleCatagory,

            Prc_RIS_ORDER_Insert,
            Prc_RIS_ORDER_Select,
            Prc_RIS_ORDER_SelectRadiologist,
            Prc_RIS_ORDER_SelectByOrderID,
            Prc_RIS_ORDER_UpdateSelfArrivalStatus,
            Prc_RIS_ORDER_Update,
            Prc_RIS_ORDER_Delete,

           
            
            Prc_RIS_ORDERDTL_Insert,
            Prc_RIS_ORDERDTL_Delete,
            Prc_RIS_ORDERDTL_SelectByOrderID,
            Prc_RIS_ORDERDTL_Update,

            Prc_RIS_Schedule_Update,
            Prc_RIS_SCHEDULE_SelectByHN,
            Prc_RIS_SCHEDULE_SelectByID,
            Prc_RIS_SCHEDULE_UpdateStatus,

            Prc_RIS_Scheduledtl_Select,
            Prc_RIS_Scheduledtl_SelectBySCHEDULE_ID,


            Prc_HIS_REGISTRATION_Select,
            Prc_RIS_EXAM_Select,
            Prc_RIS_EXAM_Insert,
            Prc_RIS_EXAM_Update,
            Prc_RIS_EXAM_Delete,
            Prc_RIS_EXAM_SelectAll,
            Prc_RIS_EXAMTYPE_Select,

            Prc_RIS_EXAMINSTRUCTIONS_Select,
            Prc_RIS_EXAMINSTRUCTIONS_SelectByExamID,
            Prc_RIS_EXAMINSTRUCTIONS_Insert,
            Prc_RIS_EXAMINSTRUCTIONS_Update,
            Prc_RIS_EXAMINSTRUCTIONS_Delete,

            Prc_RIS_MODALITY_Select,
            Prc_RIS_MODALITY_SelectAll,
            Prc_RIS_MODALITY_Insert,
            Prc_RIS_MODALITY_Update,
            Prc_RIS_MODALITY_Delete,

            Prc_RIS_MODALITYTYPE_Select,
            Prc_RIS_MODALITYEXAM_SelectAll,
            Prc_RIS_MODALITYEXAM_SelectByModalityID,
            Prc_RIS_MODALITYTYPE_Insert,
            Prc_RIS_MODALITYTYPE_Update,
            Prc_RIS_MODALITYTYPE_Delete,

            Prc_RIS_MODALITYEXAM_Select,
            Prc_RIS_MODALITYEXAM_Insert,
            Prc_RIS_MODALITYEXAM_Update,
            Prc_RIS_MODALITYEXAM_Delete,

            Prc_RIS_SERVICETYPE_Select,
            Prc_RIS_SERVICETYPE_SelectAll,
            Prc_RIS_SERVICETYPE_Insert,
            Prc_RIS_SERVICETYPE_Update,
            Prc_RIS_SERVICETYPE_Delete,

            GBLAlert_Insert,
            GBLAlert_Update,
            GBLAlert_Delete,
            GBLEnv_Update,
            GBLMenu_Select,
            GBLMenu_Update,
            GBLMenu_Insert,
            GBLMenu_Delete,
            GBLSubMenu_Select,
            GBLSubMenu_Update,
            GBLSubMenu_Insert,
            GBLSubMenu_Delete,
            GBLSubMenuObjects_Select,
            GBLSubMenuObjects_Insert,
            GBLSubMenuObjects_Update,
            GBLSubMenuObjects_Delete,
            GBLSubMenuObjectLabel_Select,
            GBLSubMenuObjectLabel_Insert,
            GBLSubMenuObjectLabel_Update,
            GBLSubMenuObjectLabel_Delete,
            GBLRole_Select,
            GBLRole_Insert,
            GBLRole_Update,
            GBLRole_Delete,
            GBLLanguage_Select,
            GBLLanguage_Delete,
            GBLLanguage_Update,
            GBLLanguage_Insert,
            GBLGrantObject_Select,
            GBLGrantObject_Inherit,
            GBLGrantObject_Delete,
            GBLGrantObject_Insert,
            GBLGrantObject_Update,
            GBLGrantRole_LoadTree,
            GBLGrantRole_Delete,
            GBLGrantRole_Insert,
            GBLGrantRole_Update,

            Prc_GBL_EMPSIGN_Delete,
            Prc_GBL_EMPSIGN_Insert,
            Prc_GBL_EMPSIGN_Select,
            Prc_GBL_EMPSIGN_Update,

            PRC_RIS_SF02_Delete,
            PRC_RIS_SF02_Insert,
            PRC_RIS_SF02_Select,
            PRC_RIS_SF02_Update,
            PRC_RIS_SF04_Delete,
            PRC_RIS_SF04_Insert,
            PRC_RIS_SF04_Select,
            PRC_RIS_SF04_Update,
            PRC_RIS_SF09_Delete,
            PRC_RIS_SF09_Insert,
            PRC_RIS_SF09_Select,
            PRC_RIS_SF09_Update,

            Prc_RISOrderConfliction,
            Prc_SplitOrder,
            Prc_HIS_DEPARTMENT_Select,
            Prc_HIS_DOCTOR_Select,
            Prc_HIS_ICD_Select,
            Prc_RIS_ACR_Select,
            Prc_RIS_AUTHLEVEL_Select,
            Prc_HR_UNIT_Select,
            Prc_RIS_ORDER_SelectRadioWork,
            Prc_HR_EMP_SelectDoctor,
            Prc_RIS_INSURANCETYPE_SelectAll,
            Prc_HIS_REGISTRATION_Insert,
            Prc_RIS_ORDER_SelectAll,
            Prc_HIS_REGISTRATION_UpdateByOrder,
            Prc_RIS_PATSTATUS_Select,
            Prc_ViewPerformance_Select,
            Prc_RIS_ORDER_SelectPreviousOrder,
            Prc_RIS_ORDER_SelectPrevious,
            Prc_RIS_ORDER_Cancel,
            Prc_HIS_SelectFromHIS,
            Prc_HIS_InsertFromHIS,
            Prc_HIS_REGISTRATION_InsertByLinkDown,
            Prc_RIS_ORDERDTL_UpdateHL7,
            Prc_RIS_CLINICTYPE_Select,
            Prc_RIS_PATICD_Select,
            Prc_RIS_PATICD_SelectByOrder,
            Prc_RIS_PATICD_Insert,
            Prc_RIS_PATICD_Update,
            Prc_RIS_PATICD_Delete,
            Prc_HIS_REGISTRATION_InsertOrUpdateFromHIS,
            GBL_Sequences_SelectRunNo,
            Prc_RIS_ORDERDTL_UpdateFlag,

            Prc_RIS_SCHEDULE_SelectByHIS,
            Prc_RIS_ORDER_SelectByHN,
            Prc_RIS_ORDER_Reprint,

            Prc_HR_EMP_GetAccount,
            Prc_HR_EMP_UpdateAccount,
            Prc_Risv_Patien_SelectData,
            Prc_Risv_Patien_SelectDataDate,
            Prc_ManageGroups_Select,
            Prc_ManageGroups_Update,
            Prc_ManageGroups_Insert,
            Prc_ManageGroups_Delete,
            Prc_ManageGroups_Select_Dtl,
            Prc_ManageGroups_Update_Dtl,
            Prc_ManageGroups_Insert_Dtl,
            Prc_ManageGroups_Delete_Dtl,
            Prc_ManageGroups_SelectGroupsTable,
            Prc_ManageGroups_SelectGroupsDtlTable,
            Prc_GrantRole_Select,
            Prc_GrantRole_Insert,
            Prc_GrantRole_Delete,
            Prc_GrantRole_Update,

            GBLEmployee_AddAccount,
            GBLEmployee_InsertAccount,
            GBLEmployee_GetAccount,
            GBLEmployee_UpdateAccount,
            GBLEmployee_DeleteAccount,

            Prc_RIS_ORDER_SelectByLastOrder,
            Prc_RIS_ORDER_REPORT,
            Prc_RIS_ORDERIMAGES_Select,
            Prc_RIS_ORDERIMAGES_UpdateStatus,
            Prc_RIS_ORDERDTL_SelectByCapture,
            Prc_RIS_ORDERDTL_SelectByQA,
            Prc_RIS_QAWORKS_Insert,
            Prc_RIS_ORDERDTL_UpdateStatus,
            Prc_RIS_TECHWORKS_InsertByStartOnly,

            Prc_RIS_TECHWORKS_Insert,
            Prc_RIS_TECHWORKS_Select,
            Prc_RIS_TECHCONSUMPTION_Select,
            Prc_RIS_TECHCONSUMPTION_Insert,
            Prc_RIS_TECHWORKS_Update,
            Prc_RIS_TECHCONSUMPTION_Delete,
            Prc_RIS_ORDERDTL_SelectByPreview,

            Prc_ResultEntry_ICD,
            Prc_EmployeeSchedule_Select,


            Prc_RIS_MODALITYEXAM_Select_rptModality,
            Prc_RIS_MODALITYEXAM_Select_rptModality_Para,
            Prc_RIS_ORDER_ReprintSticker,
            Prc_RIS_ORDER_REPORT_DURATION,
            GBL_Sequences_HNRunning,


            Prc_RIS_QAWORKS_Select_rptQAWorks,
            Prc_RIS_ORDER_GenAccession,


            Prc_RIS_ORDERDTL_Select_rptOrderDTL,

            Prc_GBLGrantRole_Delete,
            Prc_GBLGrantRole_Update,
            Prc_GBLGrantRole_Insert,
            Prc_GBLGrantRole_Select,
            Prc_GBLGrantRole_SelectByRole,
            Prc_GBLGrantRole_SelectByEmployee,
            Prc_GBLGrantRole_InsertByEmployee,
            Prc_GBLGrantRole_InsertByRole,
            Prc_GBLGrantRole_UpdateISDeleted,
            Prc_GBLGrantRole_UpdateISUpdated,

            Prc_Patient_Registration_Select,
            Prc_Patient_Registration_Insert,
            Prc_Patient_Registration_Update,
            Prc_Patient_Registration_Delete,


            Prc_RIS_TECHCONSUMPTION_History,
            Prc_RIS_EXAM_SelectConsumable,
            Prc_GBL_PRODUCT_UpdateVersion,
            Prc_RIS_ORDERIMAGES_SelectMinByOrderID,

            Prc_RIS_SIGNATURE_Select,
            Prc_RIS_RptCancellation,
            Prc_RIS_RptComparing1,
            Prc_RIS_RptComparing2,
            Prc_RIS_RptWorkload,
            Prc_RIS_RptOrder,
            Prc_RIS_RptService,
            Prc_RIS_Rpt_AppointDate,
            //Prc_EmployeeSchedule_Select,
           // Prc_RIS_QAWORKS_Select_rptQAWorks

            Prc_XRAYREQ_UpdateStatus,
            Prc_XRAYREQ_Select,

            Prc_INV_ITEM_Select,
            Prc_INV_ITEM_Insert,
            Prc_INV_ITEM_Update,
            Prc_INV_ITEM_Delete,

            Prc_INV_VENDOR_Select,
            Prc_INV_VENDOR_Insert,
            Prc_INV_VENDOR_Update,
            Prc_INV_VENDOR_Delete,

            Prc_INV_CATEGORY_Select,
            Prc_INV_CATEGORY_Insert,
            Prc_INV_CATEGORY_Update,
            Prc_INV_CATEGORY_Delete,

            Prc_INV_ITEMTYPE_Select,
            Prc_INV_ITEMTYPE_Insert,
            Prc_INV_ITEMTYPE_Update,
            Prc_INV_ITEMTYPE_Delete,

            Prc_INV_ITEMSTATUS_Select,
            Prc_INV_ITEMSTATUS_Insert,
            Prc_INV_ITEMSTATUS_Update,
            Prc_INV_ITEMSTATUS_Delete,

            Prc_INV_UNIT_Select,
            Prc_INV_UNIT_Insert,
            Prc_INV_UNIT_Update,
            Prc_INV_UNIT_Delete,

            Prc_INV_TXNUNIT_Select,
            Prc_INV_TXNUNIT_Insert,
            Prc_INV_TXNUNIT_Update,
            Prc_INV_TXNUNIT_Delete,

            Prc_INV_PO_Select,
            Prc_INV_PO_Insert,
            Prc_INV_PO_Update,
            Prc_INV_PO_Delete,

            Prc_INV_PODTL_Select,
            Prc_INV_PODTL_Insert,
            Prc_INV_PODTL_Update,
            Prc_INV_PODTL_Delete,

            Prc_INV_SETTINGS_Select,
            Prc_INV_SETTINGS_Insert,
            Prc_INV_SETTINGS_Update,
            Prc_INV_SETTINGS_Delete,

            Prc_INV_TRANSACTIONTYPE_Select,
            Prc_INV_TRANSACTIONTYPE_Insert,
            Prc_INV_TRANSACTIONTYPE_Update,
            Prc_INV_TRANSACTIONTYPE_Delete,

            Prc_INV_UNITREORDERLEVEL_Select,
            Prc_INV_UNITREORDERLEVEL_Insert,
            Prc_INV_UNITREORDERLEVEL_Update,
            Prc_INV_UNITREORDERLEVEL_Delete,

            Prc_INV_ROOMSTOCKREDUCE_Select,
            Prc_INV_ROOMSTOCKREDUCE_Insert,
            Prc_INV_ROOMSTOCKREDUCE_Update,
            Prc_INV_ROOMSTOCKREDUCE_Delete,

            Prc_INV_AUTHORISATION_Select,
            Prc_INV_AUTHORISATION_Insert,
            Prc_INV_AUTHORISATION_Update,
            Prc_INV_AUTHORISATION_Delete,

            Prc_INV_AUTHORISER_Select,
            Prc_INV_AUTHORISER_Insert,
            Prc_INV_AUTHORISER_Update,
            Prc_INV_AUTHORISER_Delete,

            Prc_INV_REQUISITION_Select,
            Prc_INV_REQUISITION_Insert,
            Prc_INV_REQUISITION_Update,
            Prc_INV_REQUISITION_Delete,

            Prc_INV_REQUISITIONDTL_Select,
            Prc_INV_REQUISITIONDTL_Insert,
            Prc_INV_REQUISITIONDTL_Update,
            Prc_INV_REQUISITIONDTL_Delete,

            Prc_INV_ITEM_Searching,

            Prc_INV_ITEMSTOCK_Select_REQMaster,
            Prc_INV_ITEMSTOCK_Select_REQDetail,
            Prc_INV_ITEMSTOCK_Select_POMaster,
            Prc_INV_ITEMSTOCK_Select_PODetail,

            Prc_INV_TRANSACTION_Insert,
            Prc_INV_ITEMSTOCK_Select_StockMaster,
            Prc_INV_ITEMSTOCK_Select_StockDetail,

            Prc_INV_PR_Delete,
            Prc_INV_PR_Insert,
            Prc_INV_PR_Select,
            Prc_INV_PR_Update,

            Prc_INV_PRDTL_Delete,
            Prc_INV_PRDTL_Insert,
            Prc_INV_PRDTL_Select,
            Prc_INV_PRDTL_Update,

            Prc_INV_AUTHORIZATION_Select,
            Prc_INV_AUTHORIZATION_Update,
            Prc_INV_AUTHORIZATION_Insert,
            Prc_INV_AUTHORIZATION_Delete,

            Prc_FIN_INVOICE_Delete,
            Prc_FIN_INVOICE_Select,
            Prc_FIN_INVOICE_Update,
            Prc_FIN_INVOICE_Insert,

            Prc_FIN_INVOICEDTL_Delete,
            Prc_FIN_INVOICEDTL_Select,
            Prc_FIN_INVOICEDTL_Update,
            Prc_FIN_INVOICEDTL_Insert,

            Prc_FIN_PAYMENT_Select,
            Prc_FIN_PAYMENT_Insert,
            Prc_FIN_PAYMENT_Update,
            Prc_FIN_PAYMENT_Delete,

            Prc_FIN_PAYMENTDTL_Select,
            Prc_FIN_PAYMENTDTL_Insert,
            Prc_FIN_PAYMENTDTL_Update,
            Prc_FIN_PAYMENTDTL_Delete,

            Prc_GBL_HOSPITAL_SelectAll,
            Prc_GBL_HOSPITAL_Insert,
            Prc_GBL_HOSPITAL_Update,
            Prc_GBL_HOSPITAL_Delete,
            Prc_HR_EMP_SelectDoctorMapping,
            Prc_GBL_HOSPITAL_DeleteMapping,
            Prc_GBL_HOSPITAL_InsertMapping,

            Prc_RIS_EXAMHOSPITAL_Delete,
            Prc_RIS_EXAMHOSPITAL_Insert,
            Prc_RIS_EXAMHOSPITAL_Select,
            Prc_RIS_EXAMHOSPITAL_Update,

            Prc_RIS_SCHEDULE_Select,
            Prc_RIS_SCHEDULE_SelectTime,
            Prc_RIS_SCHEDULE_Insert,
            Prc_RIS_SCHEDULE_InsertBlock,
            Prc_RIS_SCHEDULE_Update,
            Prc_RIS_SCHEDULE_UpdateBlock,
            Prc_RIS_SCHEDULE_UpdateTimer,
            Prc_RIS_SCHEDULE_Delete,
            Prc_RIS_SCHEDULE_Count,
            Prc_RIS_SCHEDULE_SelectHNApp,
            Prc_RIS_SCHEDULE_CheckConflict,
            Prc_RIS_SCHEDULELOG_Select,

            Prc_RIS_MODALITYCLINICTYPE_CheckMax,
            Prc_RIS_MODALITYCLINICTYPE_Select,

            Prc_DistributionNew_select,
            Prc_DistributionNew_Update,
            Prc_RIS_USERORGMAP_Select,
            Prc_RIS_USERORGMAP_Insert,
            Prc_RIS_USERORGMAP_Update,
            Prc_RIS_USERORGMAP_Delete,

            Prc_RIS_BPVIEW_Delete,
            Prc_RIS_BPVIEW_Insert,
            Prc_RIS_BPVIEW_Select,
            Prc_RIS_BPVIEW_Update,

            Prc_RIS_EXAMRESULT_Select,
            Prc_RIS_EXAMRESULT_WorkList,
            Prc_RIS_EXAMRESULT_CaseAmt,
            Prc_RIS_EXAMRESULT_History,
            Prc_RIS_EXAMRESULT_BrowseArchive_Select,
            Prc_RIS_EXAMRESULT_Transfer_Select,
            Prc_RIS_EXAMRESULT_Transfer_Update,
            Prc_RIS_EXAMRESULT_MergeSplit,
            Prc_RIS_EXAMRESULT_Reporting,
            Prc_RIS_EXAMRESULT_MergeSelect,

            Prc_RIS_EXAMRESULTTEMPLATE_Select,
            Prc_RIS_EXAMRESULTTEMPLATE_Insert,
            Prc_RIS_EXAMRESULTTEMPLATE_Delete,

            RIS_EXAMTEMPLATESHARE_SelectBy,
            Prc_RIS_EXAMTEMPLATESHARE_Insert,

            Prc_RIS_EXAMRESULTNOTE_Select,

            Prc_RIS_NURSESDATA_Select,
            Prc_RIS_NURSESDATA_Insert,
            Prc_RIS_NURSESDATA_Delete,
            Prc_RIS_NURSESDATA_Update,

            Prc_RIS_NURSESDATADTL_Select,
            Prc_RIS_NURSESDATADTL_Insert,
            Prc_RIS_NURSESDATADTL_Delete,
            Prc_RIS_NURSESDATADTL_Update,

            Prc_RIS_LOADMEDIA_Insert,
            Prc_RIS_LOADMEDIA_Select,
            Prc_RIS_LOADMEDIA_Update,
            Prc_RIS_LOADMEDIA_Delete,

            Prc_RIS_LOADMEDIADTL_Insert,
            Prc_RIS_LOADMEDIADTL_Select,
            Prc_RIS_LOADMEDIADTL_Update,
            Prc_RIS_LOADMEDIADTL_Delete,

            Prc_RIS_RELEASEMEDIA_Insert,
            Prc_RIS_RELEASEMEDIA_Select,
            Prc_RIS_RELEASEMEDIA_Update,
            Prc_RIS_RELEASEMEDIA_Delete,

            Prc_RIS_PATSTATUS_Delete,
            Prc_RIS_PATSTATUS_Insert,
            Prc_RIS_PATSTATUS_Update,
            Prc_RIS_PATSTATUSN_Select,

            Prc_GBL_RADEXPERIENCE_Delete,
            Prc_GBL_RADEXPERIENCE_Insert,
            Prc_GBL_RADEXPERIENCE_Select,
            Prc_GBL_RADEXPERIENCE_Update,

            Prc_RIS_EXAMRESULTLEGACY_Select,

            Prc_RIS_MODALITYCLINICTYPE_Delete,
            Prc_RIS_MODALITYCLINICTYPE_Insert,
            //Prc_RIS_MODALITYCLINICTYPE_Select,
            Prc_RIS_MODALITYCLINICTYPE_Update,

            Prc_RIS_EXAMRESULT_Next,
            Prc_RIS_EXAMRESULT_Previous,
            Prc_GBL_RADEXPERIENCE_Update_GridWL,
            Prc_GBL_RADEXPERIENCE_Update_GridHistory,

            Prc_RIS_SCHEDULE_Lookup,


            Prc_RIS_OPNOTEITEMTEMPLATE_Delete,
            Prc_RIS_OPNOTEITEMTEMPLATE_Select,
            Prc_RIS_OPNOTEITEMTEMPLATE_Update,
            Prc_RIS_OPNOTEITEMTEMPLATE_Insert,

            Prc_RIS_OPNOTEITEM_Delete,
            Prc_RIS_OPNOTEITEM_Select,
            Prc_RIS_OPNOTEITEM_Update,
            Prc_RIS_OPNOTEITEM_Insert,

            Prc_RIS_RADSTUDYGROUP_Delete,
            Prc_RIS_RADSTUDYGROUP_Insert,
            Prc_RIS_RADSTUDYGROUP_Select,
            Prc_RIS_RADSTUDYGROUP_Update,

            Prc_RIS_EXAMRESULTSEVERITY_Delete,
            Prc_RIS_EXAMRESULTSEVERITY_Select,
            Prc_RIS_EXAMRESULTSEVERITY_Update,
            Prc_RIS_EXAMRESULTSEVERITY_Insert,

            Prc_RIS_EXAMRESULTLOCKS_Delete,
            Prc_RIS_EXAMRESULTLOCKS_Select,
            Prc_RIS_EXAMRESULTLOCKS_Update,
            Prc_RIS_EXAMRESULTLOCKS_Insert,

            Prc_RIS_QAWORKS_Delete,
            Prc_RIS_QAWORKS_Select,
            Prc_RIS_QAWORKS_Update,

            Prc_RIS_QAREASON_Delete,
            Prc_RIS_QAREASON_Select,
            Prc_RIS_QAREASON_Update,
            Prc_RIS_QAREASON_Insert,

            Prc_RIS_INSURANCETYPE_Insert,

            Prc_RIS_EXAMTRANSFERLOG_Delete,
            Prc_RIS_EXAMTRANSFERLOG_Insert,
            Prc_RIS_EXAMTRANSFERLOG_Select,
            Prc_RIS_EXAMTRANSFERLOG_Update,

            Prc_LookUp_OrderForm_Select,
            Prc_RIS_SCHEDULEDTL_Update,
            Prc_RIS_ResendBilling,
            Prc_RIS_ORDERDTL_Send,
            Prc_HR_UNIT_Insert,
            Prc_HR_EMP_InsertFromHIS,

            Prc_RIS_EXAMRESULTLOG_Select,
            Prc_RIS_ORDERIMAGES_Update,
            Prc_RIS_CLINICSESSION_Select,

            Prc_RIS_SCHEDULE_Session,
            Prc_RIS_SCHEDULE_SelectModality,
            Prc_RIS_SCHEDULE_SessionTime,
            Prc_RIS_SCHEDULE_SelectHN,

            Prc_RIS_EXAMRESULTTEMPLATELOG_Select,
            Prc_RIS_EXAMLOG_Select,
            Prc_GBL_ENVLOG_Select,
            Prc_RIS_SCHEDULELOG_Select2,

            Prc_HR_EMP_Delete,
            Prc_HR_EMP_Insert,
            Prc_HR_EMP_Select,
            Prc_HR_EMP_Update,

            GBLLanguage_Select2,

            Prc_MIS_ASESSMENTTYPE_Delete,
            Prc_MIS_TECHNIQUETYPE_Delete,
            Prc_MIS_BIOPSYRESULT_Delete,
            Prc_MIS_LESIONTYPE_Delete,
            Prc_MIS_ASESSMENTTYPE_Insert,
            Prc_MIS_TECHNIQUETYPE_Insert,
            Prc_MIS_BIOPSYRESULT_Insert,
            Prc_MIS_LESIONTYPE_Insert,
            Prc_MIS_ASESSMENTTYPE_Select,
            Prc_MIS_TECHNIQUETYPE_Select,
            Prc_MIS_BIOPSYRESULT_Select,
            Prc_MIS_LESIONTYPE_Select,
            Prc_MIS_ASESSMENTTYPE_Update,
            Prc_MIS_TECHNIQUETYPE_Update,
            Prc_MIS_BIOPSYRESULT_Update,
            Prc_MIS_LESIONTYPE_Update,

            Prc_RIS_Rpt_BiopsyResult,
            Prc_RIS_SEARCH_Select1,
            Prc_RIS_SEARCH_Select2,
            Prc_RIS_SEARCH_Select3,

            Prc_RISV_FREQUSEDEXAM,
            Prc_GBL_Favourite_Select,
            Prc_HR_ROOM_Select,

            Prc_RIS_RELEASEMEDIA_SelectNew,

            Prc_LookUp_ReleaseCombox_Select,

            Prc_GBL_BISETTINGS_Select,
            Prc_GBL_BISETTINGS_Insert,
            Prc_GBL_BISETTINGS_Update,
            Prc_GBL_BISETTINGS_Delete,

            Prc_RIS_Rpt_Summary_DF_RateByAIMC,

            Prc_RIS_INTEGRATIONSERVERS_Select,
            Prc_RIS_INTEGRATIONCONFIG_Select,
            Prc_RIS_INTEGRATIONCONFIG_SelectCheckUnique,
            Prc_RIS_INTEGRATIONCONFIG_Update,
            Prc_RIS_INTERFACEMONITORING_Select,

            Prc_RIS_ORDER_SelectOrderReport,
            Prc_RIS_ORDERDTL_UpdatePriority,

            Prc_RIS_ORDERDTL_Update2,
        }
    }
}
 
 
 