//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;
namespace Envision.WebService.HISWebService
{
    // 
    // This source code was auto-generated by wsdl, Version=2.0.50727.3038.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "KMCHServiceSoap", Namespace = "http://tempuri.org/")]
    public partial class KMCHService : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback AboutOperationCompleted;

        private System.Threading.SendOrPostCallback KCMHConnectionOperationCompleted;

        private System.Threading.SendOrPostCallback GetDemographicByHNOperationCompleted;

        private System.Threading.SendOrPostCallback GetDemographicBySHNOperationCompleted;

        private System.Threading.SendOrPostCallback GetDemographicAddressOperationCompleted;

        private System.Threading.SendOrPostCallback GetDemographicRelationOperationCompleted;

        private System.Threading.SendOrPostCallback GetPatientAllergyOperationCompleted;

        private System.Threading.SendOrPostCallback GetDemographicInsuranceTypeOperationCompleted;

        private System.Threading.SendOrPostCallback GetXrayRequestOperationCompleted;

        private System.Threading.SendOrPostCallback GetXrayRequestByHNOperationCompleted;

        private System.Threading.SendOrPostCallback GetInsuranceAllOperationCompleted;

        private System.Threading.SendOrPostCallback GetInsuranceByCodeOperationCompleted;

        private System.Threading.SendOrPostCallback GetUnitOperationCompleted;

        private System.Threading.SendOrPostCallback GetExamOperationCompleted;

        private System.Threading.SendOrPostCallback GetExamAllOperationCompleted;

        /// <remarks/>
        public KMCHService()
        {
            this.Url = "http://ENVISIONAPP/KCMHPatientDataService/KMCHService.asmx";
        }

        /// <remarks/>
        public event AboutCompletedEventHandler AboutCompleted;

        /// <remarks/>
        public event KCMHConnectionCompletedEventHandler KCMHConnectionCompleted;

        /// <remarks/>
        public event GetDemographicByHNCompletedEventHandler GetDemographicByHNCompleted;

        /// <remarks/>
        public event GetDemographicBySHNCompletedEventHandler GetDemographicBySHNCompleted;

        /// <remarks/>
        public event GetDemographicAddressCompletedEventHandler GetDemographicAddressCompleted;

        /// <remarks/>
        public event GetDemographicRelationCompletedEventHandler GetDemographicRelationCompleted;

        /// <remarks/>
        public event GetPatientAllergyCompletedEventHandler GetPatientAllergyCompleted;

        /// <remarks/>
        public event GetDemographicInsuranceTypeCompletedEventHandler GetDemographicInsuranceTypeCompleted;

        /// <remarks/>
        public event GetXrayRequestCompletedEventHandler GetXrayRequestCompleted;

        /// <remarks/>
        public event GetXrayRequestByHNCompletedEventHandler GetXrayRequestByHNCompleted;

        /// <remarks/>
        public event GetInsuranceAllCompletedEventHandler GetInsuranceAllCompleted;

        /// <remarks/>
        public event GetInsuranceByCodeCompletedEventHandler GetInsuranceByCodeCompleted;

        /// <remarks/>
        public event GetUnitCompletedEventHandler GetUnitCompleted;

        /// <remarks/>
        public event GetExamCompletedEventHandler GetExamCompleted;

        /// <remarks/>
        public event GetExamAllCompletedEventHandler GetExamAllCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/About", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string About()
        {
            object[] results = this.Invoke("About", new object[0]);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginAbout(System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("About", new object[0], callback, asyncState);
        }

        /// <remarks/>
        public string EndAbout(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void AboutAsync()
        {
            this.AboutAsync(null);
        }

        /// <remarks/>
        public void AboutAsync(object userState)
        {
            if ((this.AboutOperationCompleted == null))
            {
                this.AboutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAboutOperationCompleted);
            }
            this.InvokeAsync("About", new object[0], this.AboutOperationCompleted, userState);
        }

        private void OnAboutOperationCompleted(object arg)
        {
            if ((this.AboutCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AboutCompleted(this, new AboutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/KCMHConnection", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool KCMHConnection()
        {
            object[] results = this.Invoke("KCMHConnection", new object[0]);
            return ((bool)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginKCMHConnection(System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("KCMHConnection", new object[0], callback, asyncState);
        }

        /// <remarks/>
        public bool EndKCMHConnection(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }

        /// <remarks/>
        public void KCMHConnectionAsync()
        {
            this.KCMHConnectionAsync(null);
        }

        /// <remarks/>
        public void KCMHConnectionAsync(object userState)
        {
            if ((this.KCMHConnectionOperationCompleted == null))
            {
                this.KCMHConnectionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKCMHConnectionOperationCompleted);
            }
            this.InvokeAsync("KCMHConnection", new object[0], this.KCMHConnectionOperationCompleted, userState);
        }

        private void OnKCMHConnectionOperationCompleted(object arg)
        {
            if ((this.KCMHConnectionCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KCMHConnectionCompleted(this, new KCMHConnectionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDemographicByHN", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetDemographicByHN(string HN)
        {
            object[] results = this.Invoke("GetDemographicByHN", new object[] {
                    HN});
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetDemographicByHN(string HN, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetDemographicByHN", new object[] {
                    HN}, callback, asyncState);
        }

        /// <remarks/>
        public System.Data.DataSet EndGetDemographicByHN(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public void GetDemographicByHNAsync(string HN)
        {
            this.GetDemographicByHNAsync(HN, null);
        }

        /// <remarks/>
        public void GetDemographicByHNAsync(string HN, object userState)
        {
            if ((this.GetDemographicByHNOperationCompleted == null))
            {
                this.GetDemographicByHNOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDemographicByHNOperationCompleted);
            }
            this.InvokeAsync("GetDemographicByHN", new object[] {
                    HN}, this.GetDemographicByHNOperationCompleted, userState);
        }

        private void OnGetDemographicByHNOperationCompleted(object arg)
        {
            if ((this.GetDemographicByHNCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDemographicByHNCompleted(this, new GetDemographicByHNCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDemographicBySHN", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetDemographicBySHN(string SHN)
        {
            object[] results = this.Invoke("GetDemographicBySHN", new object[] {
                    SHN});
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetDemographicBySHN(string SHN, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetDemographicBySHN", new object[] {
                    SHN}, callback, asyncState);
        }

        /// <remarks/>
        public System.Data.DataSet EndGetDemographicBySHN(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public void GetDemographicBySHNAsync(string SHN)
        {
            this.GetDemographicBySHNAsync(SHN, null);
        }

        /// <remarks/>
        public void GetDemographicBySHNAsync(string SHN, object userState)
        {
            if ((this.GetDemographicBySHNOperationCompleted == null))
            {
                this.GetDemographicBySHNOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDemographicBySHNOperationCompleted);
            }
            this.InvokeAsync("GetDemographicBySHN", new object[] {
                    SHN}, this.GetDemographicBySHNOperationCompleted, userState);
        }

        private void OnGetDemographicBySHNOperationCompleted(object arg)
        {
            if ((this.GetDemographicBySHNCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDemographicBySHNCompleted(this, new GetDemographicBySHNCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDemographicAddress", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetDemographicAddress(string SHN)
        {
            object[] results = this.Invoke("GetDemographicAddress", new object[] {
                    SHN});
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetDemographicAddress(string SHN, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetDemographicAddress", new object[] {
                    SHN}, callback, asyncState);
        }

        /// <remarks/>
        public System.Data.DataSet EndGetDemographicAddress(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public void GetDemographicAddressAsync(string SHN)
        {
            this.GetDemographicAddressAsync(SHN, null);
        }

        /// <remarks/>
        public void GetDemographicAddressAsync(string SHN, object userState)
        {
            if ((this.GetDemographicAddressOperationCompleted == null))
            {
                this.GetDemographicAddressOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDemographicAddressOperationCompleted);
            }
            this.InvokeAsync("GetDemographicAddress", new object[] {
                    SHN}, this.GetDemographicAddressOperationCompleted, userState);
        }

        private void OnGetDemographicAddressOperationCompleted(object arg)
        {
            if ((this.GetDemographicAddressCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDemographicAddressCompleted(this, new GetDemographicAddressCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDemographicRelation", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetDemographicRelation(string SHN)
        {
            object[] results = this.Invoke("GetDemographicRelation", new object[] {
                    SHN});
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetDemographicRelation(string SHN, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetDemographicRelation", new object[] {
                    SHN}, callback, asyncState);
        }

        /// <remarks/>
        public System.Data.DataSet EndGetDemographicRelation(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public void GetDemographicRelationAsync(string SHN)
        {
            this.GetDemographicRelationAsync(SHN, null);
        }

        /// <remarks/>
        public void GetDemographicRelationAsync(string SHN, object userState)
        {
            if ((this.GetDemographicRelationOperationCompleted == null))
            {
                this.GetDemographicRelationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDemographicRelationOperationCompleted);
            }
            this.InvokeAsync("GetDemographicRelation", new object[] {
                    SHN}, this.GetDemographicRelationOperationCompleted, userState);
        }

        private void OnGetDemographicRelationOperationCompleted(object arg)
        {
            if ((this.GetDemographicRelationCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDemographicRelationCompleted(this, new GetDemographicRelationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPatientAllergy", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetPatientAllergy(string SHN)
        {
            object[] results = this.Invoke("GetPatientAllergy", new object[] {
                    SHN});
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetPatientAllergy(string SHN, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetPatientAllergy", new object[] {
                    SHN}, callback, asyncState);
        }

        /// <remarks/>
        public System.Data.DataSet EndGetPatientAllergy(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public void GetPatientAllergyAsync(string SHN)
        {
            this.GetPatientAllergyAsync(SHN, null);
        }

        /// <remarks/>
        public void GetPatientAllergyAsync(string SHN, object userState)
        {
            if ((this.GetPatientAllergyOperationCompleted == null))
            {
                this.GetPatientAllergyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPatientAllergyOperationCompleted);
            }
            this.InvokeAsync("GetPatientAllergy", new object[] {
                    SHN}, this.GetPatientAllergyOperationCompleted, userState);
        }

        private void OnGetPatientAllergyOperationCompleted(object arg)
        {
            if ((this.GetPatientAllergyCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPatientAllergyCompleted(this, new GetPatientAllergyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDemographicInsuranceType", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetDemographicInsuranceType(string HN)
        {
            object[] results = this.Invoke("GetDemographicInsuranceType", new object[] {
                    HN});
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetDemographicInsuranceType(string HN, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetDemographicInsuranceType", new object[] {
                    HN}, callback, asyncState);
        }

        /// <remarks/>
        public System.Data.DataSet EndGetDemographicInsuranceType(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public void GetDemographicInsuranceTypeAsync(string HN)
        {
            this.GetDemographicInsuranceTypeAsync(HN, null);
        }

        /// <remarks/>
        public void GetDemographicInsuranceTypeAsync(string HN, object userState)
        {
            if ((this.GetDemographicInsuranceTypeOperationCompleted == null))
            {
                this.GetDemographicInsuranceTypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDemographicInsuranceTypeOperationCompleted);
            }
            this.InvokeAsync("GetDemographicInsuranceType", new object[] {
                    HN}, this.GetDemographicInsuranceTypeOperationCompleted, userState);
        }

        private void OnGetDemographicInsuranceTypeOperationCompleted(object arg)
        {
            if ((this.GetDemographicInsuranceTypeCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDemographicInsuranceTypeCompleted(this, new GetDemographicInsuranceTypeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetXrayRequest", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool GetXrayRequest()
        {
            object[] results = this.Invoke("GetXrayRequest", new object[0]);
            return ((bool)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetXrayRequest(System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetXrayRequest", new object[0], callback, asyncState);
        }

        /// <remarks/>
        public bool EndGetXrayRequest(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }

        /// <remarks/>
        public void GetXrayRequestAsync()
        {
            this.GetXrayRequestAsync(null);
        }

        /// <remarks/>
        public void GetXrayRequestAsync(object userState)
        {
            if ((this.GetXrayRequestOperationCompleted == null))
            {
                this.GetXrayRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetXrayRequestOperationCompleted);
            }
            this.InvokeAsync("GetXrayRequest", new object[0], this.GetXrayRequestOperationCompleted, userState);
        }

        private void OnGetXrayRequestOperationCompleted(object arg)
        {
            if ((this.GetXrayRequestCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetXrayRequestCompleted(this, new GetXrayRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetXrayRequestByHN", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool GetXrayRequestByHN(string HN)
        {
            object[] results = this.Invoke("GetXrayRequestByHN", new object[] {
                    HN});
            return ((bool)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetXrayRequestByHN(string HN, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetXrayRequestByHN", new object[] {
                    HN}, callback, asyncState);
        }

        /// <remarks/>
        public bool EndGetXrayRequestByHN(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }

        /// <remarks/>
        public void GetXrayRequestByHNAsync(string HN)
        {
            this.GetXrayRequestByHNAsync(HN, null);
        }

        /// <remarks/>
        public void GetXrayRequestByHNAsync(string HN, object userState)
        {
            if ((this.GetXrayRequestByHNOperationCompleted == null))
            {
                this.GetXrayRequestByHNOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetXrayRequestByHNOperationCompleted);
            }
            this.InvokeAsync("GetXrayRequestByHN", new object[] {
                    HN}, this.GetXrayRequestByHNOperationCompleted, userState);
        }

        private void OnGetXrayRequestByHNOperationCompleted(object arg)
        {
            if ((this.GetXrayRequestByHNCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetXrayRequestByHNCompleted(this, new GetXrayRequestByHNCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetInsuranceAll", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetInsuranceAll()
        {
            object[] results = this.Invoke("GetInsuranceAll", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetInsuranceAll(System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetInsuranceAll", new object[0], callback, asyncState);
        }

        /// <remarks/>
        public System.Data.DataSet EndGetInsuranceAll(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public void GetInsuranceAllAsync()
        {
            this.GetInsuranceAllAsync(null);
        }

        /// <remarks/>
        public void GetInsuranceAllAsync(object userState)
        {
            if ((this.GetInsuranceAllOperationCompleted == null))
            {
                this.GetInsuranceAllOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInsuranceAllOperationCompleted);
            }
            this.InvokeAsync("GetInsuranceAll", new object[0], this.GetInsuranceAllOperationCompleted, userState);
        }

        private void OnGetInsuranceAllOperationCompleted(object arg)
        {
            if ((this.GetInsuranceAllCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetInsuranceAllCompleted(this, new GetInsuranceAllCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetInsuranceByCode", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetInsuranceByCode(string c_charge)
        {
            object[] results = this.Invoke("GetInsuranceByCode", new object[] {
                    c_charge});
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetInsuranceByCode(string c_charge, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetInsuranceByCode", new object[] {
                    c_charge}, callback, asyncState);
        }

        /// <remarks/>
        public System.Data.DataSet EndGetInsuranceByCode(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public void GetInsuranceByCodeAsync(string c_charge)
        {
            this.GetInsuranceByCodeAsync(c_charge, null);
        }

        /// <remarks/>
        public void GetInsuranceByCodeAsync(string c_charge, object userState)
        {
            if ((this.GetInsuranceByCodeOperationCompleted == null))
            {
                this.GetInsuranceByCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInsuranceByCodeOperationCompleted);
            }
            this.InvokeAsync("GetInsuranceByCode", new object[] {
                    c_charge}, this.GetInsuranceByCodeOperationCompleted, userState);
        }

        private void OnGetInsuranceByCodeOperationCompleted(object arg)
        {
            if ((this.GetInsuranceByCodeCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetInsuranceByCodeCompleted(this, new GetInsuranceByCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUnit", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetUnit()
        {
            object[] results = this.Invoke("GetUnit", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetUnit(System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetUnit", new object[0], callback, asyncState);
        }

        /// <remarks/>
        public System.Data.DataSet EndGetUnit(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public void GetUnitAsync()
        {
            this.GetUnitAsync(null);
        }

        /// <remarks/>
        public void GetUnitAsync(object userState)
        {
            if ((this.GetUnitOperationCompleted == null))
            {
                this.GetUnitOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUnitOperationCompleted);
            }
            this.InvokeAsync("GetUnit", new object[0], this.GetUnitOperationCompleted, userState);
        }

        private void OnGetUnitOperationCompleted(object arg)
        {
            if ((this.GetUnitCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUnitCompleted(this, new GetUnitCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetExam", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetExam(string c_charge)
        {
            object[] results = this.Invoke("GetExam", new object[] {
                    c_charge});
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetExam(string c_charge, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetExam", new object[] {
                    c_charge}, callback, asyncState);
        }

        /// <remarks/>
        public System.Data.DataSet EndGetExam(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public void GetExamAsync(string c_charge)
        {
            this.GetExamAsync(c_charge, null);
        }

        /// <remarks/>
        public void GetExamAsync(string c_charge, object userState)
        {
            if ((this.GetExamOperationCompleted == null))
            {
                this.GetExamOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetExamOperationCompleted);
            }
            this.InvokeAsync("GetExam", new object[] {
                    c_charge}, this.GetExamOperationCompleted, userState);
        }

        private void OnGetExamOperationCompleted(object arg)
        {
            if ((this.GetExamCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetExamCompleted(this, new GetExamCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetExamAll", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetExamAll()
        {
            object[] results = this.Invoke("GetExamAll", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetExamAll(System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetExamAll", new object[0], callback, asyncState);
        }

        /// <remarks/>
        public System.Data.DataSet EndGetExamAll(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public void GetExamAllAsync()
        {
            this.GetExamAllAsync(null);
        }

        /// <remarks/>
        public void GetExamAllAsync(object userState)
        {
            if ((this.GetExamAllOperationCompleted == null))
            {
                this.GetExamAllOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetExamAllOperationCompleted);
            }
            this.InvokeAsync("GetExamAll", new object[0], this.GetExamAllOperationCompleted, userState);
        }

        private void OnGetExamAllOperationCompleted(object arg)
        {
            if ((this.GetExamAllCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetExamAllCompleted(this, new GetExamAllCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void AboutCompletedEventHandler(object sender, AboutCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AboutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal AboutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void KCMHConnectionCompletedEventHandler(object sender, KCMHConnectionCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KCMHConnectionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal KCMHConnectionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public bool Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void GetDemographicByHNCompletedEventHandler(object sender, GetDemographicByHNCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDemographicByHNCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetDemographicByHNCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public System.Data.DataSet Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void GetDemographicBySHNCompletedEventHandler(object sender, GetDemographicBySHNCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDemographicBySHNCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetDemographicBySHNCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public System.Data.DataSet Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void GetDemographicAddressCompletedEventHandler(object sender, GetDemographicAddressCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDemographicAddressCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetDemographicAddressCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public System.Data.DataSet Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void GetDemographicRelationCompletedEventHandler(object sender, GetDemographicRelationCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDemographicRelationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetDemographicRelationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public System.Data.DataSet Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void GetPatientAllergyCompletedEventHandler(object sender, GetPatientAllergyCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPatientAllergyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetPatientAllergyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public System.Data.DataSet Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void GetDemographicInsuranceTypeCompletedEventHandler(object sender, GetDemographicInsuranceTypeCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDemographicInsuranceTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetDemographicInsuranceTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public System.Data.DataSet Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void GetXrayRequestCompletedEventHandler(object sender, GetXrayRequestCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetXrayRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetXrayRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public bool Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void GetXrayRequestByHNCompletedEventHandler(object sender, GetXrayRequestByHNCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetXrayRequestByHNCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetXrayRequestByHNCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public bool Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void GetInsuranceAllCompletedEventHandler(object sender, GetInsuranceAllCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetInsuranceAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetInsuranceAllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public System.Data.DataSet Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void GetInsuranceByCodeCompletedEventHandler(object sender, GetInsuranceByCodeCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetInsuranceByCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetInsuranceByCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public System.Data.DataSet Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void GetUnitCompletedEventHandler(object sender, GetUnitCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUnitCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetUnitCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public System.Data.DataSet Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void GetExamCompletedEventHandler(object sender, GetExamCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetExamCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetExamCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public System.Data.DataSet Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void GetExamAllCompletedEventHandler(object sender, GetExamAllCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetExamAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetExamAllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public System.Data.DataSet Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}