using System.Data.Common;
using Envision.Common;
using System;

namespace Envision.DataAccess.Update
{
	public class RISIntegrationConfigUpdateData : DataAccessBase
	{
		public RIS_INTEGRATIONCONFIG RIS_INTEGRATIONCONFIG { get; set; }

		public RISIntegrationConfigUpdateData() { }

		public void Update()
		{
			StoredProcedureName = StoredProcedure.Prc_RIS_INTEGRATIONCONFIG_Update;

			ParameterList = new DbParameter[]
			{
				Parameter("@WORK_STATION_ID", RIS_INTEGRATIONCONFIG.WORK_STATION_ID),
				Parameter("@WORK_STATION_UID", RIS_INTEGRATIONCONFIG.WORK_STATION_UID),
				Parameter("@SERVER_ID", RIS_INTEGRATIONCONFIG.SERVER_ID),
				Parameter("@USE_SOCKET", RIS_INTEGRATIONCONFIG.USE_SOCKET),
				Parameter("@RECEIVER_IP", RIS_INTEGRATIONCONFIG.RECEIVER_IP),
				Parameter("@RECEIVER_PORT", RIS_INTEGRATIONCONFIG.RECEIVER_PORT == 0 ? DBNull.Value : (object)RIS_INTEGRATIONCONFIG.RECEIVER_PORT),
				Parameter("@SENDER_IP", RIS_INTEGRATIONCONFIG.SENDER_IP),
				Parameter("@WEB_SERVICE_URL", RIS_INTEGRATIONCONFIG.WEB_SERVICE_URL),
				Parameter("@SEND_ADT", RIS_INTEGRATIONCONFIG.SEND_ADT),
				Parameter("@SEND_ADT_RECONCILE", RIS_INTEGRATIONCONFIG.SEND_ADT_RECONCILE),
				Parameter("@SEND_ORM", RIS_INTEGRATIONCONFIG.SEND_ORM),
				Parameter("@SEND_ORM_BIDIRECTIONAL", RIS_INTEGRATIONCONFIG.SEND_ORM_BIDIRECTIONAL),
				Parameter("@SEND_ORM_MERGE", RIS_INTEGRATIONCONFIG.SEND_ORM_MERGE),
				Parameter("@SEND_ORU", RIS_INTEGRATIONCONFIG.SEND_ORU),
				Parameter("@SEND_ORU_WHEN_OWNER", RIS_INTEGRATIONCONFIG.SEND_ORU_WHEN_OWNER),
				Parameter("@SEND_PRELIM", RIS_INTEGRATIONCONFIG.SEND_PRELIM),
				Parameter("@RESULT_TYPE", RIS_INTEGRATIONCONFIG.RESULT_TYPE),
				Parameter("@IS_ACTIVE", RIS_INTEGRATIONCONFIG.IS_ACTIVE)
			};

			ExecuteNonQuery();
		}
	}
}
