using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Envision.DataAccess
{
    public enum StoredProcedure
    {
        #region Look up
        Prc_LookUp_Age_Select,
        Prc_LookUp_RadiologistConfig_Select,
        Prc_LookUp_OPNoteHN_Select,
        Prc_LookUp_ExamOPNote_Select,
        Prc_LookUp_RIS_RADSTUDYGROUP_Select,
        Prc_LookUp_ResultLock_Select,
        Prc_LookUp_ExamConsumable_Select,
        Prc_LookUp_JohnDoeCase_Update,
        Prc_LookUp_HeaderReport_Select,
        Prc_LookUp_EditOrder_Select,
        Prc_LookUp_XRAYREQ_SelectByHN,
        Prc_LookUp_ResultReject_Select,
        Prc_RIS_ORDER_EditOrder_Select,
        Prc_LookUp_DateStatisticMode_Select,
        Prc_LookUp_DateStatistic_Select,
        Prc_LookUp_ContrastLot_Select,
        Prc_LookUp_OrderIdByAccession_Select,
        Prc_LookUp_RegIdByScheduleId_Select,
        Prc_LookUp_RptFindingAll_Select,
        #endregion

        #region rpt_Report
        Prc_RIS_rptPR,
        Prc_RIS_rptPO,
        Prc_RIS_Rpt_PATIENT_FLOW,
        Prc_RIS_RptInvoice,
        Prc_RIS_Rpt_InvStock,
        Prc_RIS_Rpt_Summary_Schedule,
        Prc_RIS_Rpt_Summary_ResultSpecialClinic,
        Prc_RIS_Rpt_Summary_Order,
        Prc_RIS_Rpt_Summary_ScheduleByModality,
        Prc_RIS_Rpt_Summary_DF_Rate,
        Prc_RIS_Rpt_Summary_DF_RateByAIMC,
        Prc_RIS_RptCancellation,
        Prc_RIS_RptComparing1,
        Prc_RIS_RptComparing2,
        Prc_RIS_RptWorkload,
        Prc_RIS_RptOrder,
        Prc_RIS_RptService,
        Prc_RIS_Rpt_AppointDate,
        Prc_RIS_Rpt_ScheduleCountAppoint,
        Prc_RIS_SCHEDULE_XRPTREPORT,

        Prc_RIS_Rpt_ComboboxTATReport,
        Prc_RIS_Rpt_TATReport,
        Prc_RIS_Rpt_FeedBackReport,
        Prc_RIS_Rpt_SummaryDFAIMC,
        Prc_RIS_SCHEDULE_XRPTREPORT_AIMC,
        Prc_RIS_Rpt_RadiologistWorkload_AIMC,
        #endregion

        #region Academic
        Prc_AC_ASSIGNMENT_Insert,
        Prc_AC_ASSIGNMENT_Select,
        Prc_AC_ASSIGNMENT_SelectByAccessionNo,
        Prc_AC_ASSIGNMENT_SelectByAccessionWithRAD,
        Prc_AC_ASSIGNMENT_Delete,

        Prc_AC_EVALUATION_Insert,
        Prc_AC_EVALUATION_Update,
        Prc_AC_EVALUATION_Select,

        Prc_AC_YEAR_Delete,
        Prc_AC_YEAR_Insert,
        Prc_AC_YEAR_Select,
        Prc_AC_YEAR_Update,
        Prc_AC_YEAR_SelectByDatenow,

        Prc_AC_CLASS_Delete,
        Prc_AC_CLASS_Select,
        Prc_AC_CLASS_Update,
        Prc_AC_CLASS_Insert,

        Prc_AC_GRADE_Delete,
        Prc_AC_GRADE_Select,
        Prc_AC_GRADE_Update,
        Prc_AC_GRADE_Insert,

        Prc_AC_ENROLLMENT_Delete,
        Prc_AC_ENROLLMENT_Select,
        Prc_AC_ENROLLMENT_Update,
        Prc_AC_ENROLLMENT_Insert,
        Prc_AC_ENROLLMENT_SelectResident,
        Prc_AC_ENROLLMENT_SelectRadiologist,
        Prc_AC_ENROLLMENT_SelectForAssignment,
        Prc_AC_ENROLLMENT_SelectByYear,

        Prc_AC_REPORTINGLANGUAGE_SELECT,
        Prc_AC_REPORTINGLANGUAGE_INSERT,
        Prc_AC_REPORTINGLANGUAGE_UPDATE,
        Prc_AC_REPORTINGLANGUAGE_DELETE,

        Prc_RIS_ORDER_GetCaseInfo,
        #endregion

        #region RIS_REJECTCAPTURE
        Prc_RIS_REJECTCAPTURELOG_SelectByAccession,
        Prc_RIS_REJECTCAPTURELOG_Insert,
        #endregion

        Prc_RIS_EXAMRESULTTIME_Insert,
        Prc_RIS_EXAMRESULTTIME_SelectTAT,
        Prc_RIS_EXAMRESULTTIME_SelectTATExecSummary,

        Prc_RIS_OnlineArrivalWorlist,

        Prc_INV_TRANSACTIONDTL_Insert,
        Prc_INV_PO_SelectForRecieve,
        Prc_INV_PO_Select_POMaster,
        Prc_INV_PO_Select_PODetail,
        Prc_INV_TRANSACTION_CancelPOInsert,
        Prc_INV_TRANSACTION_CancelRQInsert,
        Prc_INV_ITEMSTOCK_Select,
        Prc_INV_REQUISITION_Select_REQDetail,
        Prc_INV_REQUISITION_Select_REQMaster,
        Prc_INV_REQUISITION_SelectForTranfer,

        GBL_SESSION_VIEWER_UPDATE,
        GBL_SESSION_VIEWER,

        Prc_RIS_AUTOMERGECONFIG_INSERT,
        Prc_RIS_AutoMergeConfig_Select,
        RIS_AutoMergeConfig_Update,
        Prc_RIS_AUTOMERGECONFIG_DELETE,

        Prc_FormObject_Label,
        AlertObjects_Select,
        Prc_CreateNewSession,
        Prc_CloseSession,
        Prc_ShowAlert,
        Prc_GBLLookup,
        Prc_GBLExceptionLog,
        Prc_GBLProduct,
        Prc_GBLEnv,
        Prc_GBLMyFavourite,
        Prc_GBLUserMenu,
        GBLMenu_EmpSelect,
        Prc_GBLUserSubMenu,
        Prc_MyMenu_Insert,
        Prc_MyMenu_Update,
        Prc_SetFormAccess,
        Prc_PatientReg,
        Prc_Template_Insert,
        Prc_Addendum_Insert,
        Prc_ExamResult_Insert,
        Prc_ExamResult_Update,
        Prc_RadiologistAuthLevel,
        Prc_HL7Monitoring,
        Prc_ResultStatusChange,
        Prc_ResultStatusChangeLog,
        Prc_ResultEntryWorklist,
        Prc_ResultEntryHistory,
        Prc_SessionLog_IN_OUT,
        Prc_CheckSession,
        Prc_Modality_Load,
        Prc_DistributionChannel,
        Prc_CheckExamResult,
        Prc_ExamResultFor_Insert,
        Prc_ExamResultFor_Update,
        Prc_OrderImages_Insert,
        Prc_ReportExamResult,
        Prc_RIS_SCHEDULE_REPORT,
        Prc_EmployeeScheduleCatagory,

        Prc_RIS_ORDER_Insert,
        Prc_RIS_ORDER_Select,
        Prc_RIS_ORDER_SelectRadiologist,
        Prc_RIS_ORDER_SelectByOrderID,
        Prc_RIS_ORDER_UpdateSelfArrivalStatus,
        Prc_RIS_ORDER_Update,
        Prc_RIS_ORDER_Delete,



        Prc_RIS_ORDERDTL_Insert,
        Prc_RIS_ORDERDTL_Delete,
        Prc_RIS_ORDERDTL_SelectByOrderID,
        Prc_RIS_ORDERDTL_Update,

        Prc_RIS_Schedule_Update,
        Prc_RIS_SCHEDULE_SelectByHN,
        Prc_RIS_SCHEDULE_SelectByID,
        Prc_RIS_SCHEDULE_UpdateStatus,

        Prc_RIS_Scheduledtl_Select,
        Prc_RIS_Scheduledtl_SelectBySCHEDULE_ID,


        Prc_HIS_REGISTRATION_Select,
        Prc_RIS_EXAM_Select,
        Prc_RIS_EXAM_Insert,
        Prc_RIS_EXAM_Update,
        Prc_RIS_EXAM_Delete,
        Prc_RIS_EXAM_SelectAll,
        Prc_RIS_EXAMTYPE_Select,

        Prc_RIS_EXAMINSTRUCTIONS_Select,
        Prc_RIS_EXAMINSTRUCTIONS_SelectByExamID,
        Prc_RIS_EXAMINSTRUCTIONS_Insert,
        Prc_RIS_EXAMINSTRUCTIONS_Update,
        Prc_RIS_EXAMINSTRUCTIONS_Delete,

        Prc_RIS_MODALITY_Select,
        Prc_RIS_MODALITY_SelectAll,
        Prc_RIS_MODALITY_Insert,
        Prc_RIS_MODALITY_Update,
        Prc_RIS_MODALITY_Delete,

        Prc_RIS_MODALITYTYPE_Select,
        Prc_RIS_MODALITYEXAM_SelectAll,
        Prc_RIS_MODALITYEXAM_SelectByModalityID,
        Prc_RIS_MODALITYTYPE_Insert,
        Prc_RIS_MODALITYTYPE_Update,
        Prc_RIS_MODALITYTYPE_Delete,

        Prc_RIS_MODALITYEXAM_Select,
        Prc_RIS_MODALITYEXAM_Insert,
        Prc_RIS_MODALITYEXAM_Update,
        Prc_RIS_MODALITYEXAM_Delete,

        Prc_RIS_SERVICETYPE_Select,
        Prc_RIS_SERVICETYPE_SelectAll,
        Prc_RIS_SERVICETYPE_Insert,
        Prc_RIS_SERVICETYPE_Update,
        Prc_RIS_SERVICETYPE_Delete,

        GBLAlert_Insert,
        GBLAlert_Update,
        GBLAlert_Delete,
        GBLEnv_Update,
        GBLMenu_Select,
        GBLMenu_Update,
        GBLMenu_Insert,
        GBLMenu_Delete,
        GBLSubMenu_Select,
        GBLSubMenu_Update,
        GBLSubMenu_Insert,
        GBLSubMenu_Delete,
        GBLSubMenuObjects_Select,
        GBLSubMenuObjects_Insert,
        GBLSubMenuObjects_Update,
        GBLSubMenuObjects_Delete,
        GBLSubMenuObjectLabel_Select,
        GBLSubMenuObjectLabel_Insert,
        GBLSubMenuObjectLabel_Update,
        GBLSubMenuObjectLabel_Delete,
        GBLRole_Select,
        GBLRole_Insert,
        GBLRole_Update,
        GBLRole_Delete,
        GBLLanguage_Select,
        GBLLanguage_Delete,
        GBLLanguage_Update,
        GBLLanguage_Insert,
        GBLGrantObject_Select,
        GBLGrantObject_Inherit,
        GBLGrantObject_Delete,
        GBLGrantObject_Insert,
        GBLGrantObject_Update,
        GBLGrantRole_LoadTree,
        GBLGrantRole_Delete,
        GBLGrantRole_Insert,
        GBLGrantRole_Update,

        Prc_GBL_EMPSIGN_Delete,
        Prc_GBL_EMPSIGN_Insert,
        Prc_GBL_EMPSIGN_Select,
        Prc_GBL_EMPSIGN_Update,

        PRC_RIS_SF02_Delete,
        PRC_RIS_SF02_Insert,
        PRC_RIS_SF02_Select,
        PRC_RIS_SF02_Update,
        PRC_RIS_SF04_Delete,
        PRC_RIS_SF04_Insert,
        PRC_RIS_SF04_Select,
        PRC_RIS_SF04_Update,
        PRC_RIS_SF09_Delete,
        PRC_RIS_SF09_Insert,
        PRC_RIS_SF09_Select,
        PRC_RIS_SF09_Update,

        Prc_RISOrderConfliction,
        Prc_SplitOrder,
        Prc_HIS_DEPARTMENT_Select,
        Prc_HIS_DOCTOR_Select,
        Prc_HIS_ICD_Select,
        Prc_RIS_ACR_Select,
        Prc_RIS_AUTHLEVEL_Select,
        Prc_HR_UNIT_Select,
        Prc_RIS_ORDER_SelectRadioWork,
        Prc_HR_EMP_SelectDoctor,
        Prc_RIS_INSURANCETYPE_SelectAll,
        Prc_HIS_REGISTRATION_Insert,
        Prc_RIS_ORDER_SelectAll,
        Prc_HIS_REGISTRATION_UpdateByOrder,
        Prc_HIS_REGISTRATION_UpdateAllergies2,
        Prc_HIS_REGISTRATION_UpdateByOrder2,
        Prc_RIS_PATSTATUS_Select,
        Prc_ViewPerformance_Select,
        Prc_RIS_ORDER_SelectPreviousOrder,
        Prc_RIS_ORDER_SelectPrevious,
        Prc_RIS_ORDER_Cancel,
        Prc_HIS_SelectFromHIS,
        Prc_HIS_InsertFromHIS,
        Prc_HIS_REGISTRATION_InsertByLinkDown,
        Prc_RIS_ORDERDTL_UpdateHL7,
        Prc_RIS_CLINICTYPE_Select,
        Prc_RIS_PATICD_Select,
        Prc_RIS_PATICD_SelectByOrder,
        Prc_RIS_PATICD_Insert,
        Prc_RIS_PATICD_Update,
        Prc_RIS_PATICD_Delete,
        Prc_HIS_REGISTRATION_InsertOrUpdateFromHIS,
        Prc_HIS_REGISTRATION_InsertOrUpdateFromHIS_FromRama,
        GBL_Sequences_SelectRunNo,
        Prc_RIS_ORDERDTL_UpdateFlag,

        Prc_RIS_SCHEDULE_SelectByHIS,
        Prc_RIS_ORDER_SelectByHN,
        Prc_RIS_ORDER_Reprint,

        Prc_HR_EMP_GetAccount,
        Prc_HR_EMP_UpdateAccount,
        Prc_Risv_Patien_SelectData,
        Prc_Risv_Patien_SelectDataDate,
        Prc_ManageGroups_Select,
        Prc_ManageGroups_Update,
        Prc_ManageGroups_Insert,
        Prc_ManageGroups_Delete,
        Prc_ManageGroups_Select_Dtl,
        Prc_ManageGroups_Update_Dtl,
        Prc_ManageGroups_Insert_Dtl,
        Prc_ManageGroups_Delete_Dtl,
        Prc_ManageGroups_SelectGroupsTable,
        Prc_ManageGroups_SelectGroupsDtlTable,
        Prc_GrantRole_Select,
        Prc_GrantRole_Insert,
        Prc_GrantRole_Delete,
        Prc_GrantRole_Update,

        GBLEmployee_AddAccount,
        GBLEmployee_InsertAccount,
        GBLEmployee_GetAccount,
        GBLEmployee_UpdateAccount,
        GBLEmployee_DeleteAccount,

        Prc_RIS_ORDER_SelectByLastOrder,
        Prc_RIS_ORDER_REPORT,
        Prc_RIS_ORDERIMAGES_Select,
        Prc_RIS_ORDERIMAGES_UpdateStatus,
        Prc_RIS_ORDERDTL_SelectByCapture,
        Prc_RIS_ORDERDTL_SelectByCapture2,
        Prc_RIS_ORDERDTL_SelectByQA,
        Prc_RIS_ORDERDTL_SelectByRejectPacsImage,
        Prc_RIS_ORDERDTL_SelectByRejectPacsImage_withHN,
        Prc_RIS_QAWORKS_Insert,
        Prc_RIS_ORDERDTL_UpdateStatus,
        Prc_RIS_TECHWORKS_InsertByStartOnly,

        Prc_RIS_TECHWORKS_Insert,
        Prc_RIS_TECHWORKS_Select,
        Prc_RIS_TECHWORKS_SelectByAccessionNo,
        Prc_RIS_TECHCONSUMPTION_Select,
        Prc_RIS_TECHCONSUMPTION_Insert,
        Prc_RIS_TECHWORKS_Update,
        Prc_RIS_TECHCONSUMPTION_Delete,
        Prc_RIS_ORDERDTL_SelectByPreview,

        Prc_ResultEntry_ICD,

        Prc_RIS_MODALITYEXAM_Select_rptModality,
        Prc_RIS_MODALITYEXAM_Select_rptModality_Para,
        Prc_RIS_ORDER_ReprintSticker,
        Prc_RIS_ORDER_REPORT_DURATION,
        GBL_Sequences_HNRunning,

        Prc_RIS_QAWORKS_Select_rptQAWorks,
        Prc_RIS_ORDER_GenAccession,

        Prc_RIS_ORDERDTL_Select_rptOrderDTL,

        Prc_GBLGrantRole_Delete,
        Prc_GBLGrantRole_Update,
        Prc_GBLGrantRole_Insert,
        Prc_GBLGrantRole_Select,
        Prc_GBLGrantRole_SelectByRole,
        Prc_GBLGrantRole_SelectByEmployee,
        Prc_GBLGrantRole_InsertByEmployee,
        Prc_GBLGrantRole_InsertByRole,
        Prc_GBLGrantRole_UpdateISDeleted,
        Prc_GBLGrantRole_UpdateISUpdated,

        Prc_Patient_Registration_Select,
        Prc_Patient_Registration_Insert,
        Prc_Patient_Registration_Update,
        Prc_Patient_Registration_Delete,


        Prc_RIS_TECHCONSUMPTION_History,
        Prc_RIS_EXAM_SelectConsumable,
        Prc_GBL_PRODUCT_UpdateVersion,
        Prc_RIS_ORDERIMAGES_SelectMinByOrderID,

        Prc_RIS_SIGNATURE_Select,
        Prc_XRAYREQ_UpdateStatus,
        Prc_XRAYREQ_Select,

        Prc_INV_ITEM_Select,
        Prc_INV_ITEM_Insert,
        Prc_INV_ITEM_Update,
        Prc_INV_ITEM_Delete,

        Prc_INV_VENDOR_Select,
        Prc_INV_VENDOR_Insert,
        Prc_INV_VENDOR_Update,
        Prc_INV_VENDOR_Delete,

        Prc_INV_CATEGORY_Select,
        Prc_INV_CATEGORY_Insert,
        Prc_INV_CATEGORY_Update,
        Prc_INV_CATEGORY_Delete,

        Prc_INV_ITEMTYPE_Select,
        Prc_INV_ITEMTYPE_Insert,
        Prc_INV_ITEMTYPE_Update,
        Prc_INV_ITEMTYPE_Delete,

        Prc_INV_ITEMSTATUS_Select,
        Prc_INV_ITEMSTATUS_Insert,
        Prc_INV_ITEMSTATUS_Update,
        Prc_INV_ITEMSTATUS_Delete,

        Prc_INV_UNIT_Select,
        Prc_INV_UNIT_Insert,
        Prc_INV_UNIT_Update,
        Prc_INV_UNIT_Delete,

        Prc_INV_TXNUNIT_Select,
        Prc_INV_TXNUNIT_Insert,
        Prc_INV_TXNUNIT_Update,
        Prc_INV_TXNUNIT_Delete,

        Prc_INV_PO_Select,
        Prc_INV_PO_Insert,
        Prc_INV_PO_Update,
        Prc_INV_PO_Delete,

        Prc_INV_PODTL_Select,
        Prc_INV_PODTL_Insert,
        Prc_INV_PODTL_Update,
        Prc_INV_PODTL_Delete,

        Prc_INV_SETTINGS_Select,
        Prc_INV_SETTINGS_Insert,
        Prc_INV_SETTINGS_Update,
        Prc_INV_SETTINGS_Delete,

        Prc_INV_TRANSACTIONTYPE_Select,
        Prc_INV_TRANSACTIONTYPE_Insert,
        Prc_INV_TRANSACTIONTYPE_Update,
        Prc_INV_TRANSACTIONTYPE_Delete,

        Prc_INV_UNITREORDERLEVEL_Select,
        Prc_INV_UNITREORDERLEVEL_Insert,
        Prc_INV_UNITREORDERLEVEL_Update,
        Prc_INV_UNITREORDERLEVEL_Delete,

        Prc_INV_ROOMSTOCKREDUCE_Select,
        Prc_INV_ROOMSTOCKREDUCE_Insert,
        Prc_INV_ROOMSTOCKREDUCE_Update,
        Prc_INV_ROOMSTOCKREDUCE_Delete,

        Prc_INV_AUTHORISATION_Select,
        Prc_INV_AUTHORISATION_Insert,
        Prc_INV_AUTHORISATION_Update,
        Prc_INV_AUTHORISATION_Delete,

        Prc_INV_AUTHORISER_Select,
        Prc_INV_AUTHORISER_Insert,
        Prc_INV_AUTHORISER_Update,
        Prc_INV_AUTHORISER_Delete,

        Prc_INV_REQUISITION_Select,
        Prc_INV_REQUISITION_Insert,
        Prc_INV_REQUISITION_Update,
        Prc_INV_REQUISITION_Delete,

        Prc_INV_REQUISITIONDTL_Select,
        Prc_INV_REQUISITIONDTL_Insert,
        Prc_INV_REQUISITIONDTL_Update,
        Prc_INV_REQUISITIONDTL_Delete,

        Prc_INV_ITEM_Searching,

        Prc_INV_ITEMSTOCK_Select_REQMaster,
        Prc_INV_ITEMSTOCK_Select_REQDetail,
        Prc_INV_ITEMSTOCK_Select_POMaster,
        Prc_INV_ITEMSTOCK_Select_PODetail,

        Prc_INV_TRANSACTION_Insert,
        Prc_INV_ITEMSTOCK_Select_StockMaster,
        Prc_INV_ITEMSTOCK_Select_StockDetail,

        Prc_INV_PR_Delete,
        Prc_INV_PR_Insert,
        Prc_INV_PR_Select,
        Prc_INV_PR_Update,

        Prc_INV_PRDTL_Delete,
        Prc_INV_PRDTL_Insert,
        Prc_INV_PRDTL_Select,
        Prc_INV_PRDTL_Update,

        Prc_INV_AUTHORIZATION_Select,
        Prc_INV_AUTHORIZATION_Update,
        Prc_INV_AUTHORIZATION_Insert,
        Prc_INV_AUTHORIZATION_Delete,

        Prc_FIN_INVOICE_Delete,
        Prc_FIN_INVOICE_Select,
        Prc_FIN_INVOICE_Update,
        Prc_FIN_INVOICE_Insert,

        Prc_FIN_INVOICEDTL_Delete,
        Prc_FIN_INVOICEDTL_Select,
        Prc_FIN_INVOICEDTL_Update,
        Prc_FIN_INVOICEDTL_Insert,

        Prc_FIN_PAYMENT_Select,
        Prc_FIN_PAYMENT_Insert,
        Prc_FIN_PAYMENT_Update,
        Prc_FIN_PAYMENT_Delete,

        Prc_FIN_PAYMENTDTL_Select,
        Prc_FIN_PAYMENTDTL_Insert,
        Prc_FIN_PAYMENTDTL_Update,
        Prc_FIN_PAYMENTDTL_Delete,

        Prc_GBL_HOSPITAL_SelectAll,
        Prc_GBL_HOSPITAL_Insert,
        Prc_GBL_HOSPITAL_Update,
        Prc_GBL_HOSPITAL_Delete,
        Prc_HR_EMP_SelectDoctorMapping,
        Prc_GBL_HOSPITAL_DeleteMapping,
        Prc_GBL_HOSPITAL_InsertMapping,

        Prc_RIS_EXAMHOSPITAL_Delete,
        Prc_RIS_EXAMHOSPITAL_Insert,
        Prc_RIS_EXAMHOSPITAL_Select,
        Prc_RIS_EXAMHOSPITAL_Update,

        Prc_RIS_SCHEDULE_Select,
        Prc_RIS_SCHEDULE_SelectTime,
        Prc_RIS_SCHEDULE_Insert,
        Prc_RIS_SCHEDULE_Insert_FromRama,
        Prc_RIS_SCHEDULE_InsertBlock,
        Prc_RIS_SCHEDULE_Update,
        Prc_RIS_SCHEDULE_UpdateBlock,
        Prc_RIS_SCHEDULE_UpdateBlockNew,
        Prc_RIS_SCHEDULE_UpdateTimer,
        Prc_RIS_SCHEDULE_Delete,
        Prc_RIS_SCHEDULE_Count,
        Prc_RIS_SCHEDULE_SelectHNApp,
        Prc_RIS_SCHEDULE_CheckConflict,
        Prc_RIS_SCHEDULE_CheckConflictTime,
        Prc_RIS_SCHEDULELOG_Select,

        Prc_RIS_MODALITYCLINICTYPE_CheckMax,
        Prc_RIS_MODALITYCLINICTYPE_Select,
        Prc_RIS_MODALITYCLINICTYPE_Select_InExamForm,

        Prc_DistributionNew_select,
        Prc_DistributionNew_Update,
        Prc_RIS_USERORGMAP_Select,
        Prc_RIS_USERORGMAP_Insert,
        Prc_RIS_USERORGMAP_Update,
        Prc_RIS_USERORGMAP_Delete,

        Prc_RIS_BPVIEW_Delete,
        Prc_RIS_BPVIEW_Insert,
        Prc_RIS_BPVIEW_Select,
        Prc_RIS_BPVIEW_Update,

        Prc_RIS_EXAMRESULT_Select,
        Prc_RIS_EXAMRESULT_WorkList,
        Prc_RIS_EXAMRESULT_WorkList2,
        Prc_RIS_EXAMRESULT_CaseAmt,
        Prc_RIS_EXAMRESULT_History,
        Prc_RIS_EXAMRESULT_BrowseArchive_Select,
        Prc_RIS_EXAMRESULT_Transfer_Select,
        Prc_RIS_EXAMRESULT_Transfer_Update,
        Prc_RIS_EXAMRESULT_MergeSplit,
        Prc_RIS_EXAMRESULT_Reporting,
        Prc_RIS_EXAMRESULT_MergeSelect,
        Prc_RIS_EXAMRESULT_CaseSelect,

        Prc_RIS_EXAMRESULTTEMPLATE_Select,
        Prc_RIS_EXAMRESULTTEMPLATE_Insert,
        Prc_RIS_EXAMRESULTTEMPLATE_Delete,

        RIS_EXAMTEMPLATESHARE_SelectBy,
        Prc_RIS_EXAMTEMPLATESHARE_Insert,

        Prc_RIS_EXAMRESULTNOTE_Select,

        Prc_RIS_NURSESDATA_Select,
        Prc_RIS_NURSESDATA_Insert,
        Prc_RIS_NURSESDATA_Delete,
        Prc_RIS_NURSESDATA_Update,

        Prc_RIS_NURSESDATADTL_Select,
        Prc_RIS_NURSESDATADTL_Insert,
        Prc_RIS_NURSESDATADTL_Delete,
        Prc_RIS_NURSESDATADTL_Update,

        Prc_RIS_LOADMEDIA_Insert,
        Prc_RIS_LOADMEDIA_Select,
        Prc_RIS_LOADMEDIA_Update,
        Prc_RIS_LOADMEDIA_Delete,

        Prc_RIS_LOADMEDIADTL_Insert,
        Prc_RIS_LOADMEDIADTL_Select,
        Prc_RIS_LOADMEDIADTL_Update,
        Prc_RIS_LOADMEDIADTL_Delete,

        Prc_RIS_RELEASEMEDIA_Insert,
        Prc_RIS_RELEASEMEDIA_Select,
        Prc_RIS_RELEASEMEDIA_Update,
        Prc_RIS_RELEASEMEDIA_Delete,

        Prc_RIS_PATSTATUS_Delete,
        Prc_RIS_PATSTATUS_Insert,
        Prc_RIS_PATSTATUS_Update,
        Prc_RIS_PATSTATUSN_Select,

        Prc_GBL_RADEXPERIENCE_Delete,
        Prc_GBL_RADEXPERIENCE_Insert,
        Prc_GBL_RADEXPERIENCE_Select,
        Prc_GBL_RADEXPERIENCE_Update,

        Prc_RIS_EXAMRESULTLEGACY_Select,

        Prc_RIS_MODALITYCLINICTYPE_Delete,
        Prc_RIS_MODALITYCLINICTYPE_Insert,
        //Prc_RIS_MODALITYCLINICTYPE_Select,
        Prc_RIS_MODALITYCLINICTYPE_Update,

        Prc_RIS_EXAMRESULT_Next,
        Prc_RIS_EXAMRESULT_Previous,
        Prc_GBL_RADEXPERIENCE_Update_GridWL,
        Prc_GBL_RADEXPERIENCE_Update_GridHistory,

        Prc_RIS_SCHEDULE_Lookup,


        Prc_RIS_OPNOTEITEMTEMPLATE_Delete,
        Prc_RIS_OPNOTEITEMTEMPLATE_Select,
        Prc_RIS_OPNOTEITEMTEMPLATE_Update,
        Prc_RIS_OPNOTEITEMTEMPLATE_Insert,

        Prc_RIS_OPNOTEITEM_Delete,
        Prc_RIS_OPNOTEITEM_Select,
        Prc_RIS_OPNOTEITEM_Update,
        Prc_RIS_OPNOTEITEM_Insert,

        Prc_RIS_RADSTUDYGROUP_Delete,
        Prc_RIS_RADSTUDYGROUP_Insert,
        Prc_RIS_RADSTUDYGROUP_Select,
        Prc_RIS_RADSTUDYGROUP_Update,

        Prc_RIS_EXAMRESULTSEVERITY_Delete,
        Prc_RIS_EXAMRESULTSEVERITY_Select,
        Prc_RIS_EXAMRESULTSEVERITY_Update,
        Prc_RIS_EXAMRESULTSEVERITY_Insert,

        Prc_RIS_EXAMRESULTLOCKS_Delete,
        Prc_RIS_EXAMRESULTLOCKS_Select,
        Prc_RIS_EXAMRESULTLOCKS_Update,
        Prc_RIS_EXAMRESULTLOCKS_Insert,

        Prc_RIS_QAWORKS_Delete,
        Prc_RIS_QAWORKS_Select,
        Prc_RIS_QAWORKS_Update,

        Prc_RIS_QAREASON_Delete,
        Prc_RIS_QAREASON_Select,
        Prc_RIS_QAREASON_Update,
        Prc_RIS_QAREASON_Insert,

        Prc_RIS_INSURANCETYPE_Insert,

        Prc_RIS_EXAMTRANSFERLOG_Delete,
        Prc_RIS_EXAMTRANSFERLOG_Insert,
        Prc_RIS_EXAMTRANSFERLOG_Select,
        Prc_RIS_EXAMTRANSFERLOG_Update,

        Prc_LookUp_OrderForm_Select,
        Prc_RIS_SCHEDULEDTL_Update,
        Prc_RIS_SCHEDULEDTL_UpdateNew,
        Prc_RIS_ResendBilling,
        Prc_RIS_ORDERDTL_Send,
        Prc_HR_UNIT_Insert,
        Prc_HR_EMP_InsertFromHIS,

        Prc_RIS_EXAMRESULTLOG_Select,
        Prc_RIS_ORDERIMAGES_Update,
        Prc_RIS_CLINICSESSION_Select,

        Prc_RIS_SCHEDULE_Session,
        Prc_RIS_SCHEDULE_SelectModality,
        Prc_RIS_SCHEDULE_SessionTime,
        Prc_RIS_SCHEDULE_SelectHN,
        Prc_RIS_SCHEDULE_SelectHN2,

        Prc_RIS_EXAMRESULTTEMPLATELOG_Select,
        Prc_RIS_EXAMLOG_Select,
        Prc_GBL_ENVLOG_Select,
        Prc_RIS_SCHEDULELOG_Select2,

        Prc_HR_EMP_Delete,
        Prc_HR_EMP_Insert,
        Prc_HR_EMP_Select,
        Prc_HR_EMP_Update,
        Prc_RIS_ORDERIMAGES_SelectByID,
        GBLLanguage_Select2,

        Prc_MIS_ASESSMENTTYPE_Delete,
        Prc_MIS_TECHNIQUETYPE_Delete,
        Prc_MIS_BIOPSYRESULT_Delete,
        Prc_MIS_LESIONTYPE_Delete,
        Prc_MIS_ASESSMENTTYPE_Insert,
        Prc_MIS_TECHNIQUETYPE_Insert,
        Prc_MIS_BIOPSYRESULT_Insert,
        Prc_MIS_LESIONTYPE_Insert,
        Prc_MIS_ASESSMENTTYPE_Select,
        Prc_MIS_TECHNIQUETYPE_Select,
        Prc_MIS_BIOPSYRESULT_Select,
        Prc_MIS_LESIONTYPE_Select,
        Prc_MIS_ASESSMENTTYPE_Update,
        Prc_MIS_TECHNIQUETYPE_Update,
        Prc_MIS_BIOPSYRESULT_Update,
        Prc_MIS_LESIONTYPE_Update,

        Prc_RIS_Rpt_BiopsyResult,
        Prc_RIS_SEARCH_Select1,
        Prc_RIS_SEARCH_Select2,
        Prc_RIS_SEARCH_Select3,

        Prc_RIS_SCHEDULE_LOG_Select,

        Prc_RIS_SCHEDULE_SelectMultiPrint,
        Prc_GBL_Favourite_Select,
        Prc_RIS_Rpt_OrderReportAll,

        //----------------------
        Prc_RIS_ORDER_InsertTest,
        Prc_GBL_QUICKTEXT_Delete,
        Prc_GBL_QUICKTEXT_Select,
        Prc_GBL_QUICKTEXT_Insert,
        Prc_GBL_QUICKTEXT_Update,

        Prc_RIS_ORDERDTL_SelectByCapture_withHN,
        Prc_RIS_ORDERDTL_SelectByCapture_withHN2,
        Prc_RIS_TECHWORKSDTL_Insert,


        //------------------Employee schedule
        GBLEmpSchedule_Select,
        GBLEmpSchedule_Insert,
        GBLEmpSchedule_Delete,
        GBLEmpSchedule_Update,
        Prc_LookUp_Result_Select,



        //Inventory
        Prc_INV_PR_SelectAll,
        Prc_INV_PO_SelectAll,
        Prc_INV_REQUISITION_SelectAll,
        Prc_LookUp_INV_PR_SelectForPO,



        Prc_RIS_ORDER_SelectByXrayNumber,
        Prc_HR_ROOM_Select,
        Prc_HR_ROOM_SelectBYModality,


        //New Schedule
        Prc_RIS_SCHEDULE_CheckFree,

        Prc_XREGIST_WorkList,
        Prc_XREGIST_GetRequest,
        Prc_XREGIST_Status,
        Prc_XREGIST_GetByHN,
        XREGIST_ExamInsert,

        Prc_RIS_EXAMRESULTRADS_Insert,
        Prc_RIS_EXAMRESULTRADS_Select,
        Prc_RIS_EXAMRESULTRADS_Update,
        Prc_RIS_EXAMRESULTRADS_Delete,

        Prc_RIS_FILMTRACKER_Delete,
        Prc_RIS_FILMTRACKER_Update,
        Prc_RIS_FILMTRACKER_Insert,

        Prc_RIS_FILMTRACKER_Select_ReturnForm,
        Prc_RIS_FILMTRACKER_Select_IssueForm,
        Prc_GBL_SUBMENU_Select,
        Prc_GBL_ROLE_Insert,

        Prc_RIS_ORDER_CancelTemplate,
        Prc_RIS_ORDER_Select_frmOrderIsCancel,
        Prc_RIS_ORDER_CancelwithReason,

        Prc_RIS_EXAM_Update_Barcode,
        Prc_RIS_EXAM_Select_NonInterventConsumable,
        Prc_RIS_EXAM_Select_ByBarcode,
        Prc_RIS_EXAM_Select_Intervent,

        Prc_HIS_REGISTRATION_Select_HNbyEXTHN,
        Prc_HIS_REGISTRATION_SelectAll,
        Prc_HIS_REGISTRATION_Select_LastRecord,

        Prc_RIS_MODALITYMAINTENANCETYPE_Select,
        Prc_RIS_MODALITYMAINTENANCETYPE_Insert,
        Prc_RIS_MODALITYMAINTENANCETYPE_Update,
        Prc_RIS_MODALITYMAINTENANCETYPE_Delete,

        Prc_RIS_Rpt_ModalityMaintenanceSchedule,
        Prc_RIS_MODALITYMAINTENANCESCHEDULE_Select_Worklist,
        Prc_RIS_MODALITYMAINTENANCESCHEDULE_Select_Schedule,
        Prc_RIS_MODALITYMAINTENANCESCHEDULE_Update,
        Prc_RIS_MODALITYMAINTENANCESCHEDULE_ChangeStatus,
        Prc_RIS_MODALITYMAINTENANCESCHEDULE_Insert,
        Prc_RIS_MODALITYMAINTENANCESCHEDULE_Delete,

        Prc_RIS_SCHEDULEDTL_Insert,
        Prc_RIS_SCHEDULEDTL_InsertNew,
        Prc_RIS_SCHEDULEDTL_Delete,
        Prc_RIS_EXAMPANEL_Select,

        Prc_RIS_SCHEDULE_UpdateModality,
	    Prc_XREGIST_GetByREQ,
        Prc_RIS_EXAM_SelectAll_IncludeUnActive,
        Prc_XREGIST_GetByREQDate,

        Prc_RIS_EXAMRESULTKEYIMAGES_Select,
        Prc_RIS_EXAMRESULTKEYIMAGES_Insert,
        Prc_RIS_EXAMRESULTKEYIMAGES_Delete,
        Prc_RIS_EXAMRESULTKEYIMAGES_Update,

        Prc_LookUp_ClinicalData_Select,
        Prc_RIS_BillingGenMessage,
        Prc_RIS_ORDER_UpdateEncounter,

        Prc_RIS_SCHEDULE_InsertRecurrence,
        Prc_RIS_SCHEDULE_UpdateRecurrence,

        Prc_FIN_PAYMENTDTL_UpdateStatus,

        Prc_RIS_BILLINGTRANSACTIONLOG_Insert,
        Prc_RIS_BILLINGTRANSACTIONLOGDTL_Insert,
        Prc_RIS_ORDER_Reprint_1,

        Prc_RIS_ORDER_Update_ADMISSION_NO,
        Prc_RIS_SCHEDULE_UpdatePatientStatus,
        GBL_Sequences_SelectRunNo_OnlineArrivalWorklist,
        Prc_RIS_ORDER_SelectByScan,

 	    Prc_GBL_MESSAGE_SelectByMsgID,
        Prc_GBL_MESSAGE_SelectByStatus,
        Prc_GBL_MESSAGE_Select_Trash,
        Prc_GBL_MESSAGE_Update,
        Prc_GBL_MESSAGE_Update_Star,
        Prc_GBL_MESSAGE_Update_Trash,
        Prc_GBL_MESSAGERECIPIENT_Select,
        Prc_GBL_MESSAGERECIPIENT_SelectByMsgID,
        Prc_GBL_MESSAGE_Insert,
        Prc_GBL_MESSAGERECIPIENT_Insert_Send, 
        Prc_GBL_MESSAGERECIPIENT_Update_Read,
        Prc_GBL_MESSAGERECIPIENT_Update_Star,
        Prc_GBL_MESSAGERECIPIENT_Update_Trash,
        Prc_GBL_MESSAGERECIPIENT_Check,
        Prc_HR_EMP_SelectLite,

        Prc_FIN_BILLING_SelectOrderByAccession,
        Prc_RIS_ORDERDTL_Select_Intervention,
        Prc_HR_JOBTITLE_Select,
        Prc_HR_EMP_Update_withJobTitle,
        Prc_HR_EMP_Insert_withJobTitle,

        Prc_RIS_RELEASEMEDIA_SelectNew,
        Prc_LookUp_ReleaseCombox_Select,

        // COMMENT SYSTEM
        Prc_RIS_COMMENTONPATIENT_SELECT,
        Prc_HR_EMP_GetContactList,
        Prc_RIS_ORDER_GetOrderByPatient,
        Prc_RIS_COMMENTONPATIENT_INSERT,
        Prc_RIS_COMMENTONPATIENTDTL_INSERT,
        Prc_RIS_COMMENTS_UPDATE,
        Prc_RIS_COMMENTONPATIENT_UPDATE,
        Prc_RIS_COMMENTONPATIENTDTL_UPDATE,
        //

        Prc_RIS_ORDERDTL_Select_AIMC,

        Prc_RIS_EXAMRESULTTEMPLATE_SelectById,
        Prc_RIS_EXAMRESULTTEMPLATE_AutoApply,
        Prc_RIS_MODALITY_Select_forAIMC,
        Prc_HR_UNIT_Select_forAIMC,
        Prc_RIS_PaymentChecking_Select_forAIMC,

        Prc_RIS_RPT_SummaryPaymentAIMC_Select,
        Prc_RIS_RPT_SummaryPatientAppointment_Select,
        
        Prc_RIS_EXAM_Select_AIMC,
        Prc_RIS_RPT_AIMCFinancialInvoice_Select,
        Prc_RIS_Rpt_Summary_DF_RateByTech,
        Prc_RIS_RELEASEMEDIA_Select_History,
        Prc_LookUp_AIMCInvoiceForm_Select,

        Prc_RIS_EXAMRESULT_UpdateServerity,
        Prc_RIS_MODALITY_Select_forIntervention,
        Prc_RIS_SCHEDULE_CheckFreeSlot,

        Prc_GBL_QUICKTEXT_SelectN,
        Prc_GBL_QUICKTEXT_InsertN,
        Prc_GBL_QUICKTEXT_DeleteN,
        Prc_GBL_QUICKTEXT_UpdateN,

        Prc_RIS_EXAMRESULT_WorkList_New,
        Prc_HR_UNIT_Select_forRadiologistWorklist,

        Prc_RIS_ORDER_GenAccession_NEW,

        //Structured Report

        Prc_RIS_BODYPART_Select,
        Prc_SR_TEMPLATE_SelectByExam,

        Prc_SR_QUESTIONSDTLCHILD_DeleteByPartId,

        Prc_SR_QUESTIONTYPE_Select,

        Prc_RIS_EXAM_SelectById,

        Prc_SR_TEMPLATEANSWERSPART_Insert,
        Prc_SR_TEMPLATEANSWERSPART_SelectById,
        Prc_SR_TEMPLATEANSWERSPART_SelectByAcc,

        Prc_SR_QUESTIONSANSWERS_Check,
        Prc_SR_QUESTIONSANSWERS_Clear,
        Prc_SR_QUESTIONSANSWERS_Insert,
        Prc_SR_QUESTIONSANSWERS_Update,
        Prc_SR_QUESTIONSANSWERS_Select,
        Prc_SR_QUESTIONSANSWERS_Delete,

        Prc_SR_QUESTIONSANSWERSDTL_Insert,
        Prc_SR_QUESTIONSANSWERSDTL_Update,

        Prc_SR_QUESTIONSANSWERSDTLCHILD_Insert,
        Prc_SR_QUESTIONSANSWERSDTLCHILD_Update,

        Prc_SR_USERPREFERENCE_Select,
        Prc_SR_USERPREFERENCE_SelectByEmpId,
        Prc_SR_USERPREFERENCE_SelectByExam,
        Prc_SR_USERPREFERENCE_DeleteByEmpId,
        Prc_SR_USERPREFERENCE_DeleteByTemplateId,
        Prc_SR_USERPREFERENCE_Insert,
        Prc_SR_USERPREFERENCE_InsertDefault,

        Prc_SR_TEMPLATE_Insert,
        Prc_SR_TEMPLATE_Update,
        Prc_SR_TEMPLATE_Select,
        Prc_SR_TEMPLATE_Delete,
        Prc_SR_TEMPLATE_SelectById,
        Prc_SR_QUESTIONTYPE_SELECT,
        Prc_SR_TEMPLATEPART_Insert,
        Prc_SR_TEMPLATEPART_Delete,
        Prc_SR_TEMPLATEPART_Update,
        Prc_SR_QUESTIONS_Insert,
        Prc_SR_QUESTIONS_Delete,
        Prc_SR_QUESTIONS_Update,
        Prc_SR_QUESTIONSDTL_Insert,
        Prc_SR_QUESTIONSDTL_Delete,
        Prc_SR_QUESTIONSDTL_Update,
        Prc_SR_QUESTIONSDTLCHILD_Insert,
        Prc_SR_QUESTIONSDTLCHILD_Delete,
        Prc_SR_QUESTIONSDTLCHILD_Update,

        Prc_RIS_MPPSMonitoring_Select,
        Prc_RIS_ORDERCLINICALINICATION_AND_ICD_UpdateOrderId,
        Prc_RIS_SEARCH_Select1_OrderBy_StudyDate,
        Prc_RIS_SEARCH_Select3_OrderBy_StudyDate,

        //Waiting List
        Prc_RIS_SCHEDULE_SelectTest,
        Prc_RIS_SCHEDULE_WaitingList,
        Prc_RIS_SCHEDULE_UpdateWaitingList,
        //Prc_RIS_SCHEDULE_WaitingList2,
        Prc_RIS_SCHEDULE_UpdateBusy,
        //Prc_RIS_SCHEDULE_Busy,
        Prc_RIS_SCHEDULE_Busy2,
        Prc_RIS_SCHEDULE_SessionCount,
        Prc_RIS_SCHEDULE_AppointmentCount,
        Prc_RIS_SCHEDULE_SelectBlock,

        Prc_RIS_SCHEDULECONFIG_Select,
        Prc_RIS_MODALITYEXAM_SelectByConfig,
        Prc_RIS_MODALITYCONFIG_Select,
        Prc_RIS_MODALITYCONFIG_SelectById,

        // RISK SYSTEM
        Prc_RIS_RISKCATEGORIES_SELECT,
        Prc_RIS_RISKCATEGORIES_INSERT,
        Prc_RIS_RISKCATEGORIES_UPDATE,
        Prc_RIS_RISKCATEGORIES_DELETE,

        Prc_RIS_RISKINCIDENTS_DELETE,
        Prc_RIS_RISKINCIDENTS_SELECT,
        Prc_RIS_RISKINCIDENTS_INSERT,
        Prc_RIS_RISKINCIDENTS_UPDATE,

        Prc_RIS_RISKINCIDENTUSERS_SELECT,
        Prc_RIS_RISKINCIDENTUSERS_INSERT,
        Prc_RIS_RISKINCIDENTUSERS_DELETE,

        Prc_RIS_rptRiskSystemReport,

        Prc_RIS_LABCREATININE_Select,
        Prc_RIS_LABCREATININE_Insert,
        Prc_RIS_LABCREATININE_Update,

        #region Birad System
        Prc_MG_BREASTEXAMRESULT_DELETE,
        Prc_MG_BREASTEXAMRESULT_INSERT,
        Prc_MG_BREASTEXAMRESULT_SELECT,
        Prc_MG_BREASTEXAMRESULT_UPDATE,
        Prc_MG_BREASTMASSDETAILS_DELETE,
        Prc_MG_BREASTMASSDETAILS_INSERT,
        Prc_MG_BREASTMASSDETAILS_SELECT,
        Prc_MG_BREASTMASSDETAILS_UPDATE,
        Prc_MG_PATIENTHISTORYCOMPARISON_DELETE,
        Prc_MG_PATIENTHISTORYCOMPARISON_INSERT,
        Prc_MG_PATIENTHISTORYCOMPARISON_SELECT,
        Prc_MG_PATIENTHISTORYCOMPARISON_UPDATE,
        Prc_MG_GetDemographic,
        Prc_MG_GetResultHisory,

        Prc_MG_BREASTMARK_DELETE,
        Prc_MG_BREASTMARK_INSERT,
        Prc_MG_BREASTMARK_UPDATE,
        Prc_MG_BREASTMARK_SELECT,
        Prc_MG_BREASTMARKDTL_DELETE,
        Prc_MG_BREASTMARKDTL_INSERT,

        Prc_MG_BREASTMARKTEMPLATE_Select,
        Prc_MG_BREASTMARKTEMPLATE_Insert,
        Prc_MG_BREASTMARKTEMPLATE_Update,
        Prc_MG_BREASTMARKTEMPLATE_Delete,

        Prc_MG_BREASTUSMASSDETAILS_UPDATE,
        Prc_MG_BREASTUSMASSDETAILS_INSERT,
        Prc_MG_BREASTUSMASSDETAILS_SELECT,
        Prc_MG_BREASTUSMASSDETAILS_DELETE,

        //Prc_MG_MASSDOMINANTCYST_SELECT,
        //Prc_MG_MASSDOMINANTCYST_INSERT, 
        //Prc_MG_MASSDOMINANTCYST_DELETE,
        Prc_MG_DOMINANT_Select,
        Prc_MG_DOMINANT_Insert,
        Prc_MG_DOMINANT_Delete,

        Prc_RIS_EXAMRESULT_WorkList_ByAccessionNo,
        Prc_MGStructuredReportSearch,

        Prc_RIS_ORDER_GetIsInvestigation,
        Prc_RIS_ORDER_GetOrderReport,
        Prc_RIS_ORDER_SelectOrderReport,

        Prc_AC_SUMMARY_ACADEMIC_REPORTING,
        Prc_AC_SUMMARY_BODYSYSTEM_REPORTING,
        Prc_RIS_ORDERDTL_UpdateIsDeleted,

        #endregion

        // Arrival worklist
        Prc_XRAY_Schedule_GetArrivalWorkList,
        Prc_XRAY_Schedule_GetArrivalWorkList_1,
        Prc_XRAY_Schedule_GetArrivalWorkList_2,
        Prc_XRAY_Schedule_GetArrivalWorkList_3,
        Prc_XRAY_Schedule_GetArrivalWorkList_4,
        //Prc_XRAY_GetOrderInfo,
        Prc_XRAY_GetOrderInfo2,
        Prc_RIS_PATIENTPREPARATION_SELECT,
        //Prc_RIS_SCHEDULE_GetScheduleInfo,
        Prc_RIS_SCHEDULE_GetScheduleInfo2,
        Prc_HIS_REGISTRATION_UpdateFromArrival,
        Prc_RIS_SCHEDULE_SendToOrder,
        Prc_XRAY_SendToOrder,
        Prc_RIS_ORDERDTL_UpdateHisSync,
        Prc_RIS_PATIENTDESTINATION_Select,
        Prc_RIS_ORDERDTL_Insert_v2,
        //Prc_RIS_ORDER_Insert_v2,
        Prc_RIS_ORDER_Insert_v3,
        Prc_RIS_ORDER_Get3LastOrder,

        // New order/schedule summary
        Prc_XRAY_SCHEDULE_GetSummary,
        Prc_RIS_TECHCONSUMPTION_SelectForOrderSummary,
        Prc_RIS_TECHWORKS_SelectForOrderSummary,
        Prc_RIS_ORDER_SelectForOrderSummary,
        Prc_RIS_ORDERDTL_SelectHL7Message,

        Prc_RIS_EXAMRESULT_UpdateHtml,
        Prc_RIS_SCHEDULE_UpdateNotifyAdmin,
        Prc_RIS_SCHEDULEDEFAULTDESTINATION_SelectByEmpId,
	    Prc_RIS_SCHEDULEDEFAULTDESTINATION_Insert,
	    Prc_RIS_SCHEDULEDEFAULTDESTINATION_Delete,
        Prc_RIS_EXAMRESULT_Status,


        Prc_RIS_SCHEDULEDEFAULTMODALITY_Insert,
        Prc_RIS_SCHEDULEDEFAULTMODALITY_Delete,

        Prc_RIS_EXAM_SelectDEFER_HIS_RECONCILE,
        Prc_AC_ASSIGNMENT_canAcademic,
        Prc_RIS_MODALITYEXAM_CheckDuplicateIsDefaultSelect,
        Prc_RIS_MODALITYEXAM_SelectByExamSetup,

        Prc_RIS_EXAMRESULT_SelectConsultCase,
        Prc_RIS_Rpt_Summary_DF_RateByRad_Premium,
        Prc_RIS_Rpt_Summary_DF_RateByTech_Premium,
        Prc_RIS_Rpt_Summary_DF_RateByRad_Premium2,
        Prc_RIS_Rpt_Summary_DF_RateByTech_Premium2,
        Prc_LookUp_ExamConsultCase_Select,

        Prc_RIS_RADSTUDYGROUP_InsertUpdate,
        Prc_LookUp_ACR_CPT_ICD_Select,

        Prc_AC_ASSIGNMENT_Insert_TEST,

        Prc_RIS_EXAMDF_Select,
        Prc_RIS_EXAMDF_Insert,
        Prc_RIS_EXAMDF_Update,
        Prc_RIS_EXAMDF_UpdateIsDeleted,
        Prc_HR_EMP_SelectById,

        Prc_GBL_SESSION_SelectLastKillBy,
        Prc_AC_ASSIGNMENT_CheckMerge,

        Prc_AC_EVALUATION_WorkList,
        Prc_AC_EVALUATION_WorkListByDateTime,
        Prc_AC_ASSIGNMENT_UpdateAck,

        Prc_LookUp_RadStudyManagementTags_Select,
        Prc_LookUp_RadStudyManagementBodyPart_Select,
        Prc_LookUp_RadStudyManagementCPT_Select,
        Prc_LookUp_RadStudyManagementICD_Select,
        Prc_LookUp_RadStudyManagementACR_Select,
        Prc_LookUp_RadStudyManagementConference_Select,
        Prc_LookUp_RadStudyManagementShareWith_Select,

        Prc_LookUp_MultipleAssignmentRad_Select,
        Prc_LookUp_MultipleAssignmentNurse_Select,
        Prc_LookUp_MultipleAssignmentTech_Select,

        Prc_RIS_ORDERDTL_UpdatePriority,
        Prc_RIS_Rpt_Mammogram_Summary,
        Prc_RIS_COMMENTONPATIENTDTL_SELECT,
        Prc_RIS_STUDYLIBRARY_Select,

        Prc_LookUp_PatientDestination_Select,

        Prc_GBL_BISETTINGS_Select,
        Prc_GBL_BISETTINGS_Insert,
        Prc_GBL_BISETTINGS_Update,
        Prc_GBL_BISETTINGS_Delete,

        Prc_RIS_STUDYLIBRARY_SelectNew,
        Prc_OLAPV_ORDER_Select,

        Prc_RIS_STUDYLIBRARY_Insert,

        Prc_RIS_STUDYLIBRARYDTL_Delete,
        
        Prc_RIS_STUDYLIBRARYACR_Insert,
        Prc_RIS_STUDYLIBRARYBODYPART_Insert,
        Prc_RIS_STUDYLIBRARYCPT_Insert,
        Prc_RIS_STUDYLIBRARYICD_Insert,
        Prc_RIS_STUDYLIBRARYSHAREWITH_Insert,
        Prc_RIS_STUDYLIBRARYTAGS_Insert,

        Prc_RIS_STUDYLIBRARYACR_Select,
        Prc_RIS_STUDYLIBRARYBODYPART_Select,
        Prc_RIS_STUDYLIBRARYCPT_Select,
        Prc_RIS_STUDYLIBRARYICD_Select,
        Prc_RIS_STUDYLIBRARYSHAREWITH_Select,
        Prc_RIS_STUDYLIBRARYTAGS_Select,

        Prc_RIS_STUDYLIBRARY_InsertNew,
        Prc_RIS_Rpt_ModalityWorkload_Select,

        Prc_LookUp_RadiologistWorkload,
        Prc_LookUp_SelectDatetimeNowFromSQLServer,

        Prc_HR_UNIT_Select_WithUnitType,
        Prc_RIS_Rpt_SummaryDFRad_WithModalityUnitID,

        Prc_XRAYREQDTL_CancelWithReason,

        Prc_AC_EVALUATION_WorkListNew,
        Prc_AC_EVALUATION_WorkListByDateTimeNew,
        Prc_AC_EVALUATION_GetBindData,

        Prc_RIS_Rpt_RadiologistWorkload_ER,
        Prc_RIS_SCHEDULE_AppointmentOnline,

        Prc_AC_FINALIZEPRIVILEGE_CanUserFinalize,
        Prc_AC_FINALIZEPRIVILEGE_SelectJobTitle,
        Prc_AC_FINALIZEPRIVILEGE_SelectExamTypeWithIsActive,
        Prc_AC_FINALIZEPRIVILEGE_Insert,

        Prc_RIS_EXAMRESULTSTATREPORT_Select,
        Prc_RIS_EXAMRESULTSTATREPORT_Insert,

        Prc_RIS_EXAMRESULT_CaseAmtDetail,
        Prc_GBL_GetCurrentDatetime,
        Prc_GBL_GetReportDataTimeForSynapse,
        Prc_HIS_REGISTRATION_InsertOrUpdateFromHIS_TEST,

        Prc_RIS_INTERFACEMONITORING_Select,
        Prc_RIS_INTEGRATIONCONFIG_Select,
        Prc_RIS_INTEGRATIONCONFIG_SelectCheckUnique,
        Prc_RIS_INTEGRATIONSERVERS_Select,
        Prc_RIS_INTEGRATIONCONFIG_Update,
        Prc_RIS_CLINICTYPE_UpdateByAccession,
        Prc_GBL_GENERAL_Select,
        Prc_GBL_GENERALDTL_Update,
        Prc_GBL_GENERALDTL_Delete,

        Prc_HR_UNIT_Count,
        Prc_HR_UNIT_Delete,
        Prc_HR_UNIT_InsertExcel,
        Prc_HR_UNIT_UpdateExcel,

        Prc_GBL_Errorlogs_Insert,
        Prc_GBL_Errorlogs_Update,

        Prc_RIS_EXAMRESULT_FILTERWORKLIST_Select,
        Prc_RIS_EXAMRESULT_FILTERWORKLIST_Insert,
        Prc_RIS_EXAMRESULT_FILTERWORKLIST_Update,
        Prc_RIS_EXAMRESULT_FILTERWORKLIST_Delete,

        Prc_RIS_EXAMRESULT_FILTERRAD_Select,
        Prc_RIS_EXAMRESULT_FILTERRAD_Delete,
        Prc_RIS_EXAMRESULT_FILTERRAD_Insert,

        Prc_RIS_CLINICALINDICATIONTYPE_Select2,
        Prc_RIS_CLINICALINDICATIONTYPE_All,

        Prc_GBL_Notification_Select,
        Prc_GBL_Notification_Insert,
        Prc_GBL_Notification_Update,
        Prc_GBL_Notification_Delete,

        Prc_RIS_STUDYLIBRARYCONFERENCE_Select,
        Prc_RIS_STUDYLIBRARYCONFERENCE_Insert,
        Prc_RIS_STUDYLIBRARYCONFERENCE_Delete,

        Prc_RIS_MESSAGE_Insert,
        Prc_RIS_MESSAGE_Select,
        Prc_RIS_MESSAGE_Select_PatientDetail,
        Prc_RIS_MESSAGEDTL_Insert_Reader,

        Prc_RIS_SCHEDULE_UpdatePending,
        Prc_RIS_SCHEDULE_PendingOnline,


        Prc_RIS_COMMENTSYSTEM_Insert,
        Prc_RIS_COMMENTSYSTEM_InsertBySchedule,
        Prc_RIS_COMMENTSYSTEM_InsertByXrayReq,
        Prc_RIS_COMMENTSYSTEM_Select,
        Prc_RIS_COMMENTSYSTEM_SelectForSchedule,
        Prc_RIS_COMMENTSYSTEM_SelectForXrayreq,
        Prc_RIS_COMMENTSYSTEM_Select_PatientDetail,
        Prc_RIS_COMMENTSYSTEM_SelectPatientBySchedule,
        Prc_RIS_COMMENTSYSTEM_SelectPatientByXrayreq,
        Prc_RIS_COMMENTSYSTEM_SelectDataTemplate,
        Prc_RIS_COMMENTSYSTEM_UpdateAccession,
        Prc_RIS_COMMENTSYSTEMDTL_Insert_Reader,

        Prc_RIS_ORDERDTL_SelectByCapture_withHN_Test,
        Prc_RIS_ORDERDTL_SelectByCapture_Test,

        Prc_RIS_COMMENTSYSTEM_GROUP_Delete,
        Prc_RIS_COMMENTSYSTEM_GROUP_Insert,
        Prc_RIS_COMMENTSYSTEM_GROUP_Select,
        Prc_RIS_COMMENTSYSTEM_GROUP_Update,

        Prc_RIS_COMMENTSYSTEM_GROUPDTL_Delete,
        Prc_RIS_COMMENTSYSTEM_GROUPDTL_Insert,
        Prc_RIS_COMMENTSYSTEM_GROUPDTL_Select,

        Prc_RIS_COMMENTSYSTEMALERT_Insert,
        Prc_RIS_COMMENTSYSTEMALERT_Check,
        Prc_RIS_COMMENTSYSTEMALERT_Delete,
        Prc_RIS_COMMENTSYSTEMALERT_DeleteByScheduleId,
        Prc_RIS_COMMENTSYSTEMALERT_InsertByScheduleId,
        Prc_RIS_COMMENTSYSTEMALERT_Notification,


        Prc_RIS_SCHEDULE_UpdatePendingComments,
        Prc_RIS_SCHEDULE_UpdateWaitingComments,
        Prc_Distribution_select,
        Prc_RIS_SCHEDULE_LOG_SelectNew,
        Prc_RIS_ORDERDTL_UpdateIS_DF,
        Prc_RIS_BPVIEWMAPPING_SelectNew,
        Prc_RIS_BPVIEWMAPPING_DeleteAll,
        Prc_RIS_BPVIEWMAPPING_Insert,

        Prc_RIS_SCHEDULE_SessionShow,
        Prc_RIS_SCHEDULE_InsertComments,
        Prc_RIS_SCHEDULE_UpdateComments,
        Prc_RIS_SCHEDULE_UpdateCommentsNew,
        Prc_XRAY_UpdateAccessionValue,
        Prc_RIS_COMMENTSYSTEMALERT_Count,
        Prc_RIS_SCHEDULE_SelectCaseDuration,

        Prc_RIS_EXAMRESULT_Transfer_SelectByAccession,
        Prc_RIS_EXAMRESULT_Transfer_SelectRadiologist,

        Prc_RIS_COMMENTSYSTEM_SelectForCheckGroup,
        Prc_RIS_COMMENTSYSTEM_SelectForCheckGroupByOrder,
        Prc_RIS_COMMENTSYSTEM_SelectForCheckGroupBySchedule,
        Prc_RIS_COMMENTSYSTEM_SelectForCheckGroupXrayReq,
        Prc_RIS_COMMENTSYSTEM_GROUP_SelectALLEmp,
        Prc_RIS_COMMENTSYSTEM_GROUP_SelectForCheckDefault,
        Prc_RIS_COMMENTSYSTEM_UpdateCompletedByXrayReq,
        Prc_RIS_COMMENTSYSTEM_UpdateCompletedBySchedule,
        Prc_RIS_COMMENTSYSTEM_SelectByScheduleID,
        Prc_RIS_COMMENTSYSTEM_SelectByScheduleID2,
        Prc_RIS_EXAMTRANSFERLOG_SelectByAccession,
        Prc_RIS_EXAMTRANSFERLOG_SelectByHN,
        Prc_RIS_SCHEDULE_OnlineStatCase,
        Prc_RIS_EXAMRESULTSEVERITYLOG_Select,
        Prc_RIS_EXAMRESULTSEVERITYLOG_Insert,

        Prc_RIS_UNLOCKED_Select,
        Prc_RIS_UNLOCKED_Update,
        Prc_RIS_MODALITYEXAM_ONL_SelectByModalityID,
        Prc_RIS_MODALITYEXAM_ONL_Insert,
        Prc_RIS_MODALITYEXAM_ONL_Delete,
        Prc_RIS_MODALITYEXAM_ONL_Update,

        Prc_RIS_COMMENTSYSTEMDTL_Insert_ReaderByAccession,
        Prc_RIS_COMMENTSYSTEMDTL_Insert_ReaderBySchedule,
        Prc_RIS_COMMENTSYSTEMDTL_Insert_ReaderByXrayreq,

        Prc_RIS_COMMENTSYSTEMALERT_InsertByAccession,
        Prc_RIS_COMMENTSYSTEMALERT_InsertBySchedule,
        Prc_RIS_COMMENTSYSTEMALERT_InsertByXrayreq,

        Prc_HIS_REGISTRATION_InsertOrUpdateADTChange,
        Prc_RIS_EXAMRESULT_UpdateServerityLog,

        Prc_RIS_RISKCATEGORIES_SELECTbyPRECAUTION,
        Prc_RIS_RISKCATEGORIES_SELECTbyCONTRAINDICATION,
        Prc_RIS_RISKCATEGORIES_SELECTbyCT,
        Prc_RIS_RISKCATEGORIES_SELECTbyMRI,
        Prc_RIS_RISKINCIDENTS_DELETEbyREG_ID,
        Prc_RIS_RISKINCIDENTS_SELECTbyREG_ID,

        //Prc_RIS_SCHEDULE_SelectWorklist,
        Prc_RIS_SCHEDULE_SelectWorklist3,
        Prc_RIS_EXAMPANELPORTABLE_Select,
        Prc_RIS_SCHEDULELOGS_Select2,
        Prc_RIS_SCHEDULELOGS_Insert,
        Prc_RIS_SCHEDULELOGSDTL_Insert,
        Prc_RIS_RISKINCIDENTS_SELECTbyScheduleID,
        Prc_RIS_RISKINCIDENTS_SELECTbyOrderID,
        Prc_RIS_RISKINCIDENTS_SELECTbyXRAYREQID,

        Prc_RIS_RISKINCIDENTS_DELETEbyScheduleID,
        Prc_RIS_RISKINCIDENTS_DELETEbyOrderID,
        Prc_RIS_RISKINCIDENTS_DELETEbyXrayreqID,

        Prc_RIS_SCHEDULE_WorkList_Reporting,
        Prc_RIS_SCHEDULE_WorkList_Reporting2,
        Prc_RIS_Rpt_ScheduleCountAppointWithSession,
        Prc_RIS_SCHEDULE_UpdateModalityAndSession,
        Prc_RIS_EXAMPANELPORTABLE_SelectAll,
        Prc_RIS_SCHEDULE_UpdateSessionID,
        Prc_RIS_SCHEDULE_UpdateDragDrop,
        Prc_RIS_SCHEDULE_UpdateTextShow,
        Prc_RIS_EXAMRESULT_HistoryNew,
        Prc_RIS_EXAMRESULT_HistoryReport,
        Prc_RIS_EXAMRESULT_Demographic,
        Prc_HR_EMP_SelectDoctorByID,
        Prc_HR_UNIT_SelectByID,
        Prc_RIS_SCHEDULE_SelectByXrayreqID,
        Prc_RIS_SCHEDULE_SelectByXrayreqAndModality,

        Prc_XRAYREQ_UpdateCancel,
        Prc_XRAYREQDTL_UpdateDelete,
        Prc_RIS_SESSIONMAXAPP_SelectByModality,
        Prc_RIS_SCHEDULE_TransferClinicalInstruction,
        Prc_RIS_ORDEREXAMFLAG_SelectDetail,
        Prc_RIS_ORDEREXAMFLAG_Select,
        Prc_RIS_ORDEREXAMFLAG_Insert,
        Prc_RIS_ORDEREXAMFLAG_Update,
        Prc_RIS_ORDEREXAMFLAG_SelectSchedule,
        Prc_RIS_ORDEREXAMFLAG_SelectXrayreq,

        Prc_RIS_SESSIONMAXAPP_SelectSetup,
        Prc_RIS_SESSIONMAXAPP_Update,

        Prc_RIS_PRSTUDIES_SELECTWorklist,
        Prc_RIS_PRSTUDIES_SelectResult,
        Prc_RIS_PRGRADE_Select,


        Prc_RIS_PRGROUP_Delete,
        Prc_RIS_PRGROUP_Insert,
        Prc_RIS_PRGROUP_Select,
        Prc_RIS_PRGROUP_SelectALLEmp,
        Prc_RIS_PRGROUP_SelectGroupPrStudies,
        Prc_RIS_PRGROUP_SelectGroupPrStudiesByGroupIdAndAlgorithmId,
        Prc_RIS_PRGROUP_ChkGroupName,
        Prc_RIS_PRGROUP_Update,
        Prc_RIS_PRGROUPDTL_Delete,
        Prc_RIS_PRGROUPDTL_Insert,
        Prc_RIS_PRGROUPDTL_Select,


        Prc_RIS_PRSTUDIES_Insert,
        Prc_RIS_PRSTUDIES_Delete,
        Prc_RIS_PRSTUDIES_Update,


        Prc_RIS_PRAlgorithm_SelectCT,
        Prc_RIS_PRALGORITHM_SelectGeneralUltrasound,
        Prc_RIS_PRALGORITHM_SelectDataByAlgorithyID,
        Prc_RIS_PRALGORITHM_Select,
        Prc_RIS_PRALGORITHM_Delete,
        Prc_RIS_PRALGORITHM_Insert,
      
        Prc_RIS_SCHEDULE_SelectMergeCase,
        Prc_RIS_SCHEDULE_SelectMergeCaseDtl,
        Prc_RIS_SCHEDULE_UpdateAppointmentMerge,
        Prc_RIS_SCHEDULE_SelectMergeConflict,

        Prc_RIS_SCHEDULE_SessionByModality,
        Prc_XRAYREQ_SelectMergeRequest,
        Prc_XRAYREQDTL_Insert,
        Prc_XRAYREQ_UpdateMergeRequest,

        Prc_RIS_SCHEDULE_RESERVATION_Insert,
        Prc_RIS_SCHEDULE_RESERVATION_Delete,

        Prc_RIS_SCHEDULE_UpdateRequestResult,
        Prc_RIS_ORDER_UpdateRequestResult,
        Prc_RIS_BILLINGLOG_WITH_HIS_Insert,
        Prc_RIS_BILLINGLOG_WITH_HIS_Select,
        Prc_RIS_BILLINGLOGDTL_BY_HIS_Insert,
        Prc_RIS_BILLINGLOGDTL_BY_HIS_Insert2,
        Prc_RIS_BILLINGLOG_WITH_HIS_ERRORCLINIC_Insert,
        Prc_RIS_EXAMRESULTSEVERITYLOG_Insert2,
        Prc_RIS_SESSIONAPPCOUNT_SelectIsBlock,
        Prc_RIS_SESSIONAPPCOUNT_UpdateIsBlock,
        Prc_RIS_SCHEDULE_ShowOnline,
        Prc_RIS_SCHEDULE_ShowOnline2,
        Prc_GBL_Errorlogs_InsertNew,
        AAA_SCHEDULELOG_insert,
        Prc_RIS_EXAMINSTRUCTIONCLINICSESSION_SelectByExamAndSession,
        Prc_RIS_EXAMINSTRUCTIONCLINICSESSION_UpdateOrInsert,
        Prc_HR_TITLE_Select,
        Prc_RIS_COMMENTSYSTEM_CheckForSchedule,
        Prc_RIS_PATSTATUS_SelectActive,
        Prc_RIS_ORDERIMAGES_Insert,
        Prc_RIS_ORDERIMAGES_UpdateIsDeleted,
        Prc_RIS_SCHEDULE_UpdateIsProtocalByTech,
        Prc_RIS_SCHEDULE_UpdateSchedulePending,
        Prc_RIS_COMMENTSYSTEM_UpdateStatus,
        Prc_XRAYREQ_UpdateBusyCase,
        Prc_XRAYREQ_SelectBusyCase,
        Prc_RIS_ORDERCLINICALINICATION_UpdateOrderIdByScheduleId,
        Prc_RIS_RISKINCIDENTS_UpdateOrderIdByScheduleId,
        Prc_RIS_ORDERIMAGES_UpdateOrderIdByScheduleId,
        Prc_LookUp_AIImageLink_Select,
        Prc_LookUp_AIImageLink_SelectMulti,
        Prc_RIS_RESULTSTATUSCHANGELOG_Select,

        Prc_LookUp_ContrastManagement_Select,
        Prc_GBL_QUICKTEXT_SelectFilterMode,
        Prc_ContrastAcuteReaction_Select,
        Prc_RIS_Contrastdtl_Select,

        Prc_RIS_CONTRASTDTL_Insert,
        Prc_RIS_CONTRASTDTL_Update,
        Prc_RIS_CONTRASTDTL_UpdateArrival,
        Prc_RIS_CONTRASTDTL_Delete,
        Prc_RIS_CONTRASTDTL_Select,
        Prc_RIS_CONTRASTDTL_SelectByDate,
        Prc_RIS_CONTRASTDTL_SelectByOrderId,
        Prc_RIS_CONTRASTDTL_SelectByScheduleId,
        Prc_RIS_CONTRASTDTL_SelectByRegId,
        Prc_RIS_CONTRASTDTL_SelectByHn,

        Prc_RIS_CONTRASTLOT_Insert,
        Prc_RIS_CONTRASTLOT_Update,
        Prc_RIS_CONTRASTLOT_Select,

        Prc_RIS_CONTRASTLOTMAPPING_Select,
        Prc_RIS_CONTRASTLOTMAPPING_Insert,
        Prc_RIS_CONTRASTLOTMAPPING_Delete,
        Prc_RIS_EXAMRESULT_WorkListCovid,
        Prc_RIS_EXAMRESULT_DTL_Insert,
        Prc_RIS_TECHWORKSDTL_InsertWithRads,

        Prc_RIS_EXAMMAPBILLING_Insert,
        Prc_RIS_EXAMMAPBILLING_Select,
        Prc_RIS_EXAMMAPBILLING_Delete,

        Prc_RIS_BillingGenMessageMulti,
        Prc_RIS_TECHWORKSDTLRAD_Insert,
        Prc_HR_EMP_AD_InsertFromHIS,
        Prc_GBLGrantRole_AD_SelectByEmployee,
        Prc_RIS_EXAMRESULT_AD_WorkList,
        Prc_RIS_EXAMRESULT_CaseAmt_AD,
        Prc_RIS_EXAMRESULT_CaseAmtDetail_AD,

        #region Preparing Change

        Prc_RIS_EXAMRESULTSTATREPORT_Insert_New,
        Prc_RIS_EXAMRESULT_Reporting2,
        Prc_CreateNewSession2,
        Prc_RIS_SCHEDULE_SelectWorklist2,
        Prc_ResultStatusChangeLog2,
        Prc_XRAY_Schedule_GetArrivalWorkList_TEST,
        #endregion
    }
}
