//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.9151
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Envision.NET.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Envision.NET.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _01entry {
            get {
                object obj = ResourceManager.GetObject("_01entry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01entry_24 {
            get {
                object obj = ResourceManager.GetObject("_01entry_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01entry_48 {
            get {
                object obj = ResourceManager.GetObject("_01entry_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap aadc47389e {
            get {
                object obj = ResourceManager.GetObject("aadc47389e", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap activity {
            get {
                object obj = ResourceManager.GetObject("activity", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap add_24 {
            get {
                object obj = ResourceManager.GetObject("add_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap add_48 {
            get {
                object obj = ResourceManager.GetObject("add_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ai {
            get {
                object obj = ResourceManager.GetObject("ai", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap alert_16 {
            get {
                object obj = ResourceManager.GetObject("alert_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BG01 {
            get {
                object obj = ResourceManager.GetObject("BG01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap browse_16 {
            get {
                object obj = ResourceManager.GetObject("browse_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap browse_24 {
            get {
                object obj = ResourceManager.GetObject("browse_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap browse_48 {
            get {
                object obj = ResourceManager.GetObject("browse_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap business_intelligence32 {
            get {
                object obj = ResourceManager.GetObject("business_intelligence32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Calculator_16 {
            get {
                object obj = ResourceManager.GetObject("Calculator_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap calculator_orange24 {
            get {
                object obj = ResourceManager.GetObject("calculator_orange24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap caution {
            get {
                object obj = ResourceManager.GetObject("caution", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap check_document16 {
            get {
                object obj = ResourceManager.GetObject("check_document16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap circle {
            get {
                object obj = ResourceManager.GetObject("circle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap close {
            get {
                object obj = ResourceManager.GetObject("close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Comment_add_icon16 {
            get {
                object obj = ResourceManager.GetObject("Comment_add_icon16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Comment_add_icon32 {
            get {
                object obj = ResourceManager.GetObject("Comment_add_icon32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Comment_add_icon48 {
            get {
                object obj = ResourceManager.GetObject("Comment_add_icon48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Compass {
            get {
                object obj = ResourceManager.GetObject("Compass", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap confirmation {
            get {
                object obj = ResourceManager.GetObject("confirmation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CYC24 {
            get {
                object obj = ResourceManager.GetObject("CYC24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Designer_workstation {
            get {
                object obj = ResourceManager.GetObject("Designer_workstation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap draw_star {
            get {
                object obj = ResourceManager.GetObject("draw_star", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Envision {
            get {
                object obj = ResourceManager.GetObject("Envision", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap envision_login {
            get {
                object obj = ResourceManager.GetObject("envision_login", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap envision_Login2 {
            get {
                object obj = ResourceManager.GetObject("envision_Login2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap envision_splashscreen {
            get {
                object obj = ResourceManager.GetObject("envision_splashscreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap envision04 {
            get {
                object obj = ResourceManager.GetObject("envision04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap exit32 {
            get {
                object obj = ResourceManager.GetObject("exit32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceSheet24 {
            get {
                object obj = ResourceManager.GetObject("FaceSheet24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon favicon {
            get {
                object obj = ResourceManager.GetObject("favicon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap favourite_16 {
            get {
                object obj = ResourceManager.GetObject("favourite_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_favorites {
            get {
                object obj = ResourceManager.GetObject("folder_favorites", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_labs {
            get {
                object obj = ResourceManager.GetObject("folder-labs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap font {
            get {
                object obj = ResourceManager.GetObject("font", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap font_plus {
            get {
                object obj = ResourceManager.GetObject("font_plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gmail_icon128 {
            get {
                object obj = ResourceManager.GetObject("gmail_icon128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gmail_icon128_NewMessage {
            get {
                object obj = ResourceManager.GetObject("gmail_icon128_NewMessage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap go_cut {
            get {
                object obj = ResourceManager.GetObject("go_cut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gridBG {
            get {
                object obj = ResourceManager.GetObject("gridBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Help {
            get {
                object obj = ResourceManager.GetObject("Help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Help1 {
            get {
                object obj = ResourceManager.GetObject("Help1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap history_16 {
            get {
                object obj = ResourceManager.GetObject("history_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap history_24 {
            get {
                object obj = ResourceManager.GetObject("history_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap history_48 {
            get {
                object obj = ResourceManager.GetObject("history_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap home {
            get {
                object obj = ResourceManager.GetObject("home", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Home_16 {
            get {
                object obj = ResourceManager.GetObject("Home_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_add {
            get {
                object obj = ResourceManager.GetObject("icon_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_adminstrator {
            get {
                object obj = ResourceManager.GetObject("icon_adminstrator", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_adminstrator32 {
            get {
                object obj = ResourceManager.GetObject("icon_adminstrator32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_del {
            get {
                object obj = ResourceManager.GetObject("icon_del", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_faavourite {
            get {
                object obj = ResourceManager.GetObject("icon_faavourite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_help {
            get {
                object obj = ResourceManager.GetObject("icon_help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_help16 {
            get {
                object obj = ResourceManager.GetObject("icon_help16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_home {
            get {
                object obj = ResourceManager.GetObject("icon_home", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_home32 {
            get {
                object obj = ResourceManager.GetObject("icon_home32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_myforum {
            get {
                object obj = ResourceManager.GetObject("icon_myforum", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_newarrival {
            get {
                object obj = ResourceManager.GetObject("icon_newarrival", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_order {
            get {
                object obj = ResourceManager.GetObject("icon_order", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_order32 {
            get {
                object obj = ResourceManager.GetObject("icon_order32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_report {
            get {
                object obj = ResourceManager.GetObject("icon_report", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_report32 {
            get {
                object obj = ResourceManager.GetObject("icon_report32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_reprint {
            get {
                object obj = ResourceManager.GetObject("icon_reprint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_result {
            get {
                object obj = ResourceManager.GetObject("icon_result", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_result32 {
            get {
                object obj = ResourceManager.GetObject("icon_result32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_schedule {
            get {
                object obj = ResourceManager.GetObject("icon_schedule", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_schedule32 {
            get {
                object obj = ResourceManager.GetObject("icon_schedule32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_viewperformance {
            get {
                object obj = ResourceManager.GetObject("icon_viewperformance", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icoWL_Accept {
            get {
                object obj = ResourceManager.GetObject("icoWL_Accept", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icoWL_Alert {
            get {
                object obj = ResourceManager.GetObject("icoWL_Alert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap information {
            get {
                object obj = ResourceManager.GetObject("information", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap key {
            get {
                object obj = ResourceManager.GetObject("key", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap key2 {
            get {
                object obj = ResourceManager.GetObject("key2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Login {
            get {
                object obj = ResourceManager.GetObject("Login", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap logoff32 {
            get {
                object obj = ResourceManager.GetObject("logoff32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap logojf {
            get {
                object obj = ResourceManager.GetObject("logojf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon logojf1 {
            get {
                object obj = ResourceManager.GetObject("logojf1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mail_delete_2 {
            get {
                object obj = ResourceManager.GetObject("mail_delete_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mail_forward_5 {
            get {
                object obj = ResourceManager.GetObject("mail_forward_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mail_mark_unread_new {
            get {
                object obj = ResourceManager.GetObject("mail_mark_unread_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mail_message_send_icon48 {
            get {
                object obj = ResourceManager.GetObject("mail-message-send-icon48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mail_new {
            get {
                object obj = ResourceManager.GetObject("mail_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mail_read {
            get {
                object obj = ResourceManager.GetObject("mail_read", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mail_reply_all_3 {
            get {
                object obj = ResourceManager.GetObject("mail_reply_all_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mail_reply_all_5 {
            get {
                object obj = ResourceManager.GetObject("mail_reply_all_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mail_reply_sender_2 {
            get {
                object obj = ResourceManager.GetObject("mail_reply_sender_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mail_reply_sender_3 {
            get {
                object obj = ResourceManager.GetObject("mail_reply_sender_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mail_send_2 {
            get {
                object obj = ResourceManager.GetObject("mail_send_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menuAcedemic {
            get {
                object obj = ResourceManager.GetObject("menuAcedemic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menuOlap {
            get {
                object obj = ResourceManager.GetObject("menuOlap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menuRisk {
            get {
                object obj = ResourceManager.GetObject("menuRisk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menuStructure {
            get {
                object obj = ResourceManager.GetObject("menuStructure", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap merge {
            get {
                object obj = ResourceManager.GetObject("merge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap merge_16 {
            get {
                object obj = ResourceManager.GetObject("merge_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap merge_24 {
            get {
                object obj = ResourceManager.GetObject("merge_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap merge_48 {
            get {
                object obj = ResourceManager.GetObject("merge_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Miracle05 {
            get {
                object obj = ResourceManager.GetObject("Miracle05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap new_from_last_order2_32 {
            get {
                object obj = ResourceManager.GetObject("new_from_last_order2_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap new_from_last_order2_48 {
            get {
                object obj = ResourceManager.GetObject("new_from_last_order2_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap new_read_from_template2_16 {
            get {
                object obj = ResourceManager.GetObject("new_read_from_template2_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NO_MEDICAMENTOS {
            get {
                object obj = ResourceManager.GetObject("NO-MEDICAMENTOS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Notepad_Icon {
            get {
                object obj = ResourceManager.GetObject("Notepad_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Notes24 {
            get {
                object obj = ResourceManager.GetObject("Notes24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ocwen_circle {
            get {
                object obj = ResourceManager.GetObject("ocwen_circle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap order {
            get {
                object obj = ResourceManager.GetObject("order", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon Outlook2003 {
            get {
                object obj = ResourceManager.GetObject("Outlook2003", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pendingIcon48 {
            get {
                object obj = ResourceManager.GetObject("pendingIcon48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap personal_schedule32 {
            get {
                object obj = ResourceManager.GetObject("personal_schedule32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap picAlarmBG {
            get {
                object obj = ResourceManager.GetObject("picAlarmBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pill_bottle_allergy_16 {
            get {
                object obj = ResourceManager.GetObject("pill-bottle-allergy-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap priority1_24 {
            get {
                object obj = ResourceManager.GetObject("priority1_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap priority1_48 {
            get {
                object obj = ResourceManager.GetObject("priority1_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap priority2_24 {
            get {
                object obj = ResourceManager.GetObject("priority2_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap priority2_48 {
            get {
                object obj = ResourceManager.GetObject("priority2_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap QA {
            get {
                object obj = ResourceManager.GetObject("QA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap QI24 {
            get {
                object obj = ResourceManager.GetObject("QI24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ramaai_logo_16 {
            get {
                object obj = ResourceManager.GetObject("ramaai_logo_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap refresh {
            get {
                object obj = ResourceManager.GetObject("refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap reporting_management2_32 {
            get {
                object obj = ResourceManager.GetObject("reporting_management2_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap reprint_48 {
            get {
                object obj = ResourceManager.GetObject("reprint_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap result {
            get {
                object obj = ResourceManager.GetObject("result", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rightclick_changeModality {
            get {
                object obj = ResourceManager.GetObject("rightclick_changeModality", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rightclick_delete {
            get {
                object obj = ResourceManager.GetObject("rightclick_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rightclick_lab {
            get {
                object obj = ResourceManager.GetObject("rightclick_lab", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rightclick_mail {
            get {
                object obj = ResourceManager.GetObject("rightclick_mail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rightclick_open {
            get {
                object obj = ResourceManager.GetObject("rightclick_open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rightclick_print {
            get {
                object obj = ResourceManager.GetObject("rightclick_print", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rightclick_printPreview {
            get {
                object obj = ResourceManager.GetObject("rightclick_printPreview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rightclick_viewImage {
            get {
                object obj = ResourceManager.GetObject("rightclick_viewImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap save_as_prelim16 {
            get {
                object obj = ResourceManager.GetObject("save_as_prelim16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap save_as_result16 {
            get {
                object obj = ResourceManager.GetObject("save_as_result16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap save_as_template16 {
            get {
                object obj = ResourceManager.GetObject("save_as_template16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap save_draft {
            get {
                object obj = ResourceManager.GetObject("save_draft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap save_draft_16 {
            get {
                object obj = ResourceManager.GetObject("save_draft_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap save_finalize {
            get {
                object obj = ResourceManager.GetObject("save_finalize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap save_prelim {
            get {
                object obj = ResourceManager.GetObject("save_prelim", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap save_prelim_16 {
            get {
                object obj = ResourceManager.GetObject("save_prelim_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap save_result_16 {
            get {
                object obj = ResourceManager.GetObject("save_result_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap save_template {
            get {
                object obj = ResourceManager.GetObject("save_template", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap save_template_16 {
            get {
                object obj = ResourceManager.GetObject("save_template_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Schedule {
            get {
                object obj = ResourceManager.GetObject("Schedule", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Shape {
            get {
                object obj = ResourceManager.GetObject("Shape", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap splash_screen1 {
            get {
                object obj = ResourceManager.GetObject("splash_screen1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap split {
            get {
                object obj = ResourceManager.GetObject("split", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap split_16 {
            get {
                object obj = ResourceManager.GetObject("split_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap split_24 {
            get {
                object obj = ResourceManager.GetObject("split_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap split_48 {
            get {
                object obj = ResourceManager.GetObject("split_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stroke {
            get {
                object obj = ResourceManager.GetObject("stroke", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap styleL {
            get {
                object obj = ResourceManager.GetObject("styleL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap synapse16 {
            get {
                object obj = ResourceManager.GetObject("synapse16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap syringe {
            get {
                object obj = ResourceManager.GetObject("syringe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap technologist32 {
            get {
                object obj = ResourceManager.GetObject("technologist32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap title_bar {
            get {
                object obj = ResourceManager.GetObject("title_bar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tranfer {
            get {
                object obj = ResourceManager.GetObject("tranfer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap transfer_16 {
            get {
                object obj = ResourceManager.GetObject("transfer_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap transfer_24 {
            get {
                object obj = ResourceManager.GetObject("transfer_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap transfer_48 {
            get {
                object obj = ResourceManager.GetObject("transfer_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap trash_empty_2 {
            get {
                object obj = ResourceManager.GetObject("trash_empty_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Undo__1_ {
            get {
                object obj = ResourceManager.GetObject("Undo (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap view_restore {
            get {
                object obj = ResourceManager.GetObject("view_restore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap viewtree {
            get {
                object obj = ResourceManager.GetObject("viewtree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap viewtree_16 {
            get {
                object obj = ResourceManager.GetObject("viewtree_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap viewtree_24 {
            get {
                object obj = ResourceManager.GetObject("viewtree_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap viewtree_48 {
            get {
                object obj = ResourceManager.GetObject("viewtree_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Wait_icon16 {
            get {
                object obj = ResourceManager.GetObject("Wait_icon16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Wait_icon32 {
            get {
                object obj = ResourceManager.GetObject("Wait_icon32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap warning {
            get {
                object obj = ResourceManager.GetObject("warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
