//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.3038.
// 

namespace Envision.WebService.PACSService
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "ORUMessageSoap", Namespace = "http://tempuri.org/")]
    public partial class ORUMessage : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback ORUQueueMessageOperationCompleted;

        /// <remarks/>
        public ORUMessage()
        {
            this.Url = "http://MIRACLE99/ORUQueue/ORUMessage.asmx";
        }

        /// <remarks/>
        public event ORUQueueMessageCompletedEventHandler ORUQueueMessageCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ORUQueueMessage", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ORUQueueMessage(string ACCESSION_NO)
        {
            this.Invoke("ORUQueueMessage", new object[] {
                    ACCESSION_NO});
        }

        /// <remarks/>
        public System.IAsyncResult BeginORUQueueMessage(string ACCESSION_NO, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("ORUQueueMessage", new object[] {
                    ACCESSION_NO}, callback, asyncState);
        }

        /// <remarks/>
        public void EndORUQueueMessage(System.IAsyncResult asyncResult)
        {
            this.EndInvoke(asyncResult);
        }

        /// <remarks/>
        public void ORUQueueMessageAsync(string ACCESSION_NO)
        {
            this.ORUQueueMessageAsync(ACCESSION_NO, null);
        }

        /// <remarks/>
        public void ORUQueueMessageAsync(string ACCESSION_NO, object userState)
        {
            if ((this.ORUQueueMessageOperationCompleted == null))
            {
                this.ORUQueueMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnORUQueueMessageOperationCompleted);
            }
            this.InvokeAsync("ORUQueueMessage", new object[] {
                    ACCESSION_NO}, this.ORUQueueMessageOperationCompleted, userState);
        }

        private void OnORUQueueMessageOperationCompleted(object arg)
        {
            if ((this.ORUQueueMessageCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ORUQueueMessageCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void ORUQueueMessageCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}