using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace EnvisionOnline.DataAccess
{
    public enum StoredProcedure
    {
        #region Look up
        Prc_LookUp_Age_Select,
        Prc_LookUp_RadiologistConfig_Select,
        Prc_LookUp_OPNoteHN_Select,
        Prc_LookUp_ExamOPNote_Select,
        Prc_LookUp_RIS_RADSTUDYGROUP_Select,
        Prc_LookUp_ResultLock_Select,
        Prc_LookUp_ExamConsumable_Select,
        Prc_LookUp_JohnDoeCase_Update,
        Prc_LookUp_HeaderReport_Select,
        Prc_LookUp_EditOrder_Select,
        Prc_LookUp_XRAYREQ_SelectByHN,
        Prc_LookUp_ResultReject_Select,
        Prc_LookUp_ResultSeverity_Select,
        Prc_LookUp_ReleaseCombox_Select,
        Prc_HR_JOBTITLE_Select,
        Prc_Patient_RegistrationSearch_Select,
        Prc_LookUp_PatientInOrder_Select,
        Prc_LookUp_OrderForm_CheckDataToday,
        #endregion

        #region rpt_Report
        Prc_RIS_rptPR,
        Prc_RIS_rptPO,
        Prc_RIS_Rpt_PATIENT_FLOW,
        Prc_RIS_RptInvoice,
        Prc_RIS_Rpt_InvStock,
        Prc_RIS_Rpt_Summary_Schedule,
        Prc_RIS_Rpt_Summary_ResultSpecialClinic,
        Prc_RIS_Rpt_Summary_Order,
        Prc_RIS_Rpt_Summary_ScheduleByModality,
        Prc_RIS_Rpt_Summary_DF_Rate,
        Prc_RIS_Rpt_Summary_DF_RateByAIMC,
        Prc_RIS_RptCancellation,
        Prc_RIS_RptComparing1,
        Prc_RIS_RptComparing2,
        Prc_RIS_RptWorkload,
        Prc_RIS_RptOrder,
        Prc_RIS_RptService,
        Prc_RIS_Rpt_AppointDate,
        Prc_RIS_Rpt_ScheduleCountAppoint,
        Prc_RIS_Rpt_AllCombobox,
        Prc_RIS_Rpt_TechExamReport,
        Prc_RIS_ORDER_ReportBilling,
        Prc_RIS_SCHEDULE_XRPTREPORT,
        Prc_RIS_SCHEDULE_REPORTN,
        #endregion
        Prc_RIS_BPVIEWMAPPING_Select,
        Prc_RIS_OnlineArrivalWorlist,
        Prc_RIS_EXAMRESULT_CaseSelect,
        Prc_RIS_EXAMRESULT_Status,
        Prc_RIS_EXAMRESULT_SelectConsultCase,

        Prc_RIS_EXAM_SelectConsumable,

        GBL_SESSION_VIEWER_UPDATE,
        GBL_SESSION_VIEWER,

        Prc_RIS_AUTOMERGECONFIG_INSERT,
        Prc_RIS_AutoMergeConfig_Select,
        RIS_AutoMergeConfig_Update,
        Prc_RIS_AUTOMERGECONFIG_DELETE,

        Prc_FormObject_Label,
        AlertObjects_Select,
        Prc_CreateNewSession,
        Prc_CloseSession,
        Prc_ShowAlert,
        Prc_GBLLookup,
        Prc_GBLExceptionLog,
        Prc_GBLProduct,
        Prc_GBLEnv,
        Prc_GBLMyFavourite,
        Prc_GBLUserMenu,
        GBLMenu_EmpSelect,
        Prc_GBLUserSubMenu,
        Prc_MyMenu_Insert,
        Prc_MyMenu_Update,
        Prc_SetFormAccess,
        Prc_PatientReg,
        Prc_Template_Insert,
        Prc_Addendum_Insert,
        Prc_ExamResult_Insert,
        Prc_ExamResult_Update,
        Prc_RadiologistAuthLevel,
        Prc_HL7Monitoring,
        Prc_ResultStatusChange,
        Prc_ResultStatusChangeLog,
        Prc_ResultEntryWorklist,
        Prc_ResultEntryHistory,
        Prc_SessionLog_IN_OUT,
        Prc_CheckSession,
        Prc_Modality_Load,
        Prc_DistributionChannel,
        Prc_CheckExamResult,
        Prc_ExamResultFor_Insert,
        Prc_ExamResultFor_Update,
        Prc_OrderImages_Insert,
        Prc_ReportExamResult,
        Prc_RIS_SCHEDULE_REPORT,
        Prc_EmployeeScheduleCatagory,

        Prc_RIS_ORDER_Insert,
        Prc_RIS_ORDER_Select,
        Prc_RIS_ORDER_SelectRadiologist,
        Prc_RIS_ORDER_SelectByOrderID,
        Prc_RIS_ORDER_UpdateSelfArrivalStatus,
        Prc_RIS_ORDER_Update,
        Prc_RIS_ORDER_Delete,



        Prc_RIS_ORDERDTL_Insert,
        Prc_RIS_ORDERDTL_Delete,
        Prc_RIS_ORDERDTL_SelectByOrderID,
        Prc_RIS_ORDERDTL_Update,

        Prc_RIS_Schedule_Update,
        Prc_RIS_SCHEDULE_SelectByHN,
        Prc_RIS_SCHEDULE_SelectByID,
        Prc_RIS_SCHEDULE_UpdateStatus,

        Prc_RIS_Scheduledtl_Select,
        Prc_RIS_Scheduledtl_SelectBySCHEDULE_ID,


        Prc_HIS_REGISTRATION_Select,
        Prc_RIS_EXAM_Select,
        Prc_RIS_EXAM_Insert,
        Prc_RIS_EXAM_Update,
        Prc_RIS_EXAM_Delete,
        Prc_RIS_EXAM_SelectAll,
        Prc_RIS_EXAMTYPE_Select,

        Prc_RIS_EXAMINSTRUCTIONS_Select,
        Prc_RIS_EXAMINSTRUCTIONS_SelectByExamID,
        Prc_RIS_EXAMINSTRUCTIONS_Insert,
        Prc_RIS_EXAMINSTRUCTIONS_Update,
        Prc_RIS_EXAMINSTRUCTIONS_Delete,

        Prc_RIS_MODALITY_Select,
        Prc_RIS_MODALITY_SelectAll,
        Prc_RIS_MODALITY_Insert,
        Prc_RIS_MODALITY_Update,
        Prc_RIS_MODALITY_Delete,

        Prc_RIS_MODALITYTYPE_Select,
        Prc_RIS_MODALITYEXAM_SelectAll,
        Prc_RIS_MODALITYEXAM_SelectByModalityID,
        Prc_RIS_MODALITYTYPE_Insert,
        Prc_RIS_MODALITYTYPE_Update,
        Prc_RIS_MODALITYTYPE_Delete,

        Prc_RIS_MODALITYEXAM_Select,
        Prc_RIS_MODALITYEXAM_Insert,
        Prc_RIS_MODALITYEXAM_Update,
        Prc_RIS_MODALITYEXAM_Delete,

        Prc_RIS_SERVICETYPE_Select,
        Prc_RIS_SERVICETYPE_SelectAll,
        Prc_RIS_SERVICETYPE_Insert,
        Prc_RIS_SERVICETYPE_Update,
        Prc_RIS_SERVICETYPE_Delete,

        GBLAlert_Insert,
        GBLAlert_Update,
        GBLAlert_Delete,
        GBLEnv_Update,
        GBLMenu_Select,
        GBLMenu_Update,
        GBLMenu_Insert,
        GBLMenu_Delete,
        GBLSubMenu_Select,
        GBLSubMenu_Update,
        GBLSubMenu_Insert,
        GBLSubMenu_Delete,
        GBLSubMenuObjects_Select,
        GBLSubMenuObjects_Insert,
        GBLSubMenuObjects_Update,
        GBLSubMenuObjects_Delete,
        GBLSubMenuObjectLabel_Select,
        GBLSubMenuObjectLabel_Insert,
        GBLSubMenuObjectLabel_Update,
        GBLSubMenuObjectLabel_Delete,
        GBLRole_Select,
        GBLRole_Insert,
        GBLRole_Update,
        GBLRole_Delete,
        GBLLanguage_Select,
        GBLLanguage_Delete,
        GBLLanguage_Update,
        GBLLanguage_Insert,
        GBLGrantObject_Select,
        GBLGrantObject_Inherit,
        GBLGrantObject_Delete,
        GBLGrantObject_Insert,
        GBLGrantObject_Update,
        GBLGrantRole_LoadTree,
        GBLGrantRole_Delete,
        GBLGrantRole_Insert,
        GBLGrantRole_Update,

        Prc_GBL_EMPSIGN_Delete,
        Prc_GBL_EMPSIGN_Insert,
        Prc_GBL_EMPSIGN_Select,
        Prc_GBL_EMPSIGN_Update,

        PRC_RIS_SF02_Delete,
        PRC_RIS_SF02_Insert,
        PRC_RIS_SF02_Select,
        PRC_RIS_SF02_Update,
        PRC_RIS_SF04_Delete,
        PRC_RIS_SF04_Insert,
        PRC_RIS_SF04_Select,
        PRC_RIS_SF04_Update,
        PRC_RIS_SF09_Delete,
        PRC_RIS_SF09_Insert,
        PRC_RIS_SF09_Select,
        PRC_RIS_SF09_Update,

        Prc_RISOrderConfliction,
        Prc_SplitOrder,
        Prc_HIS_DEPARTMENT_Select,
        Prc_HIS_DOCTOR_Select,
        Prc_HIS_ICD_Select,
        Prc_RIS_ACR_Select,
        Prc_RIS_AUTHLEVEL_Select,
        Prc_HR_UNIT_Select,
        Prc_RIS_ORDER_SelectRadioWork,
        Prc_HR_EMP_SelectDoctor,
        Prc_RIS_INSURANCETYPE_SelectAll,
        Prc_HIS_REGISTRATION_Insert,
        Prc_RIS_ORDER_SelectAll,
        Prc_HIS_REGISTRATION_UpdateByOrder,
        Prc_RIS_PATSTATUS_Select,
        Prc_ViewPerformance_Select,
        Prc_RIS_ORDER_SelectPreviousOrder,
        Prc_RIS_ORDER_SelectPrevious,
        Prc_RIS_ORDER_Cancel,
        Prc_HIS_SelectFromHIS,
        Prc_HIS_InsertFromHIS,
        Prc_HIS_REGISTRATION_InsertByLinkDown,
        Prc_RIS_ORDERDTL_UpdateHL7,
        Prc_RIS_CLINICTYPE_Select,
        Prc_RIS_PATICD_Select,
        Prc_RIS_PATICD_SelectByOrder,
        Prc_RIS_PATICD_Insert,
        Prc_RIS_PATICD_Update,
        Prc_RIS_PATICD_Delete,
        Prc_HIS_REGISTRATION_InsertOrUpdateFromHIS,
        GBL_Sequences_SelectRunNo,
        Prc_RIS_ORDERDTL_UpdateFlag,

        Prc_RIS_SCHEDULE_SelectByHIS,
        Prc_RIS_ORDER_SelectByHN,
        Prc_RIS_ORDER_Reprint,

        Prc_HR_EMP_GetAccount,
        Prc_HR_EMP_UpdateAccount,
        Prc_Risv_Patien_SelectData,
        Prc_Risv_Patien_SelectDataDate,
        Prc_ManageGroups_Select,
        Prc_ManageGroups_Update,
        Prc_ManageGroups_Insert,
        Prc_ManageGroups_Delete,
        Prc_ManageGroups_Select_Dtl,
        Prc_ManageGroups_Update_Dtl,
        Prc_ManageGroups_Insert_Dtl,
        Prc_ManageGroups_Delete_Dtl,
        Prc_ManageGroups_SelectGroupsTable,
        Prc_ManageGroups_SelectGroupsDtlTable,
        Prc_GrantRole_Select,
        Prc_GrantRole_Insert,
        Prc_GrantRole_Delete,
        Prc_GrantRole_Update,

        GBLEmployee_AddAccount,
        GBLEmployee_InsertAccount,
        GBLEmployee_GetAccount,
        GBLEmployee_UpdateAccount,
        GBLEmployee_DeleteAccount,

        Prc_RIS_ORDER_SelectByLastOrder,
        Prc_RIS_ORDER_REPORT,
        Prc_RIS_ORDERIMAGES_Select,
        Prc_RIS_ORDERIMAGES_UpdateStatus,
        Prc_RIS_ORDERDTL_SelectByCapture,
        Prc_RIS_ORDERDTL_SelectByQA,
        Prc_RIS_QAWORKS_Insert,
        Prc_RIS_ORDERDTL_UpdateStatus,
        Prc_RIS_TECHWORKS_InsertByStartOnly,

        Prc_RIS_TECHWORKS_Insert,
        Prc_RIS_TECHWORKS_Select,
        Prc_RIS_TECHCONSUMPTION_Select,
        Prc_RIS_TECHCONSUMPTION_Insert,
        Prc_RIS_TECHWORKS_Update,
        Prc_RIS_TECHCONSUMPTION_Delete,
        Prc_RIS_ORDERDTL_SelectByPreview,

        Prc_ResultEntry_ICD,
        Prc_EmployeeSchedule_Select,

        Prc_RIS_MODALITYEXAM_Select_rptModality,
        Prc_RIS_MODALITYEXAM_Select_rptModality_Para,
        Prc_RIS_ORDER_ReprintSticker,
        Prc_RIS_ORDER_REPORT_DURATION,
        GBL_Sequences_HNRunning,

        Prc_RIS_QAWORKS_Select_rptQAWorks,
        Prc_RIS_ORDER_GenAccession,

        Prc_RIS_ORDERDTL_Select_rptOrderDTL,

        Prc_GBLGrantRole_Delete,
        Prc_GBLGrantRole_Update,
        Prc_GBLGrantRole_Insert,
        Prc_GBLGrantRole_Select,
        Prc_GBLGrantRole_SelectByRole,
        Prc_GBLGrantRole_SelectByEmployee,
        Prc_GBLGrantRole_InsertByEmployee,
        Prc_GBLGrantRole_InsertByRole,
        Prc_GBLGrantRole_UpdateISDeleted,
        Prc_GBLGrantRole_UpdateISUpdated,

        Prc_Patient_Registration_Select,
        Prc_Patient_Registration_Insert,
        Prc_Patient_Registration_Update,
        Prc_Patient_Registration_Delete,

        Prc_RIS_SCHEDULE_Select,
        Prc_RIS_SCHEDULE_SelectTime,
        Prc_RIS_SCHEDULE_Insert,
        Prc_RIS_SCHEDULE_InsertBlock,
        Prc_RIS_SCHEDULE_Update,
        Prc_RIS_SCHEDULE_UpdateBlock,
        Prc_RIS_SCHEDULE_UpdateTimer,
        Prc_RIS_SCHEDULE_Count,
        Prc_RIS_SCHEDULE_SelectHNApp,
        Prc_RIS_SCHEDULE_CheckConflict,
        Prc_RIS_SCHEDULELOG_Select,

        Prc_RIS_MODALITYCLINICTYPE_CheckMax,
        Prc_RIS_MODALITYCLINICTYPE_Select,
        Prc_RIS_MODALITYCLINICTYPE_Select_InExamForm,

        Prc_DistributionNew_select,
        Prc_DistributionNew_Update,
        Prc_RIS_USERORGMAP_Select,
        Prc_RIS_USERORGMAP_Insert,
        Prc_RIS_USERORGMAP_Update,
        Prc_RIS_USERORGMAP_Delete,

        Prc_RIS_BPVIEW_Delete,
        Prc_RIS_BPVIEW_Insert,
        Prc_RIS_BPVIEW_Select,
        Prc_RIS_BPVIEW_Update,

        Prc_RIS_EXAMRESULT_Select,
        Prc_RIS_EXAMRESULT_WorkList,
        Prc_RIS_EXAMRESULT_CaseAmt,
        Prc_RIS_EXAMRESULT_History,
        Prc_RIS_EXAMRESULT_BrowseArchive_Select,
        Prc_RIS_EXAMRESULT_Transfer_Select,
        Prc_RIS_EXAMRESULT_Transfer_Update,
        Prc_RIS_EXAMRESULT_MergeSplit,
        Prc_RIS_EXAMRESULT_Reporting,
        Prc_RIS_EXAMRESULT_MergeSelect,

        Prc_RIS_EXAMRESULTTEMPLATE_Select,
        Prc_RIS_EXAMRESULTTEMPLATE_Insert,
        Prc_RIS_EXAMRESULTTEMPLATE_Delete,

        RIS_EXAMTEMPLATESHARE_SelectBy,
        Prc_RIS_EXAMTEMPLATESHARE_Insert,

        Prc_RIS_EXAMRESULTNOTE_Select,

        Prc_RIS_PATSTATUS_Delete,
        Prc_RIS_PATSTATUS_Insert,
        Prc_RIS_PATSTATUS_Update,
        Prc_RIS_PATSTATUSN_Select,

        Prc_GBL_RADEXPERIENCE_Delete,
        Prc_GBL_RADEXPERIENCE_Insert,
        Prc_GBL_RADEXPERIENCE_Select,
        Prc_GBL_RADEXPERIENCE_Update,

        Prc_RIS_EXAMRESULTLEGACY_Select,

        Prc_RIS_MODALITYCLINICTYPE_Delete,
        Prc_RIS_MODALITYCLINICTYPE_Insert,
        //Prc_RIS_MODALITYCLINICTYPE_Select,
        Prc_RIS_MODALITYCLINICTYPE_Update,

        Prc_RIS_EXAMRESULT_Next,
        Prc_RIS_EXAMRESULT_Previous,
        Prc_GBL_RADEXPERIENCE_Update_GridWL,
        Prc_GBL_RADEXPERIENCE_Update_GridHistory,

        Prc_RIS_SCHEDULE_Lookup,

        Prc_RIS_INSURANCETYPE_Insert,

        Prc_RIS_EXAMTRANSFERLOG_Delete,
        Prc_RIS_EXAMTRANSFERLOG_Insert,
        Prc_RIS_EXAMTRANSFERLOG_Select,
        Prc_RIS_EXAMTRANSFERLOG_Update,

        Prc_LookUp_OrderForm_Select,
        Prc_RIS_SCHEDULEDTL_Update,
        Prc_RIS_ResendBilling,
        Prc_RIS_ORDERDTL_Send,
        Prc_HR_UNIT_Insert,
        Prc_HR_EMP_InsertFromHIS,

        Prc_RIS_EXAMRESULTLOG_Select,
        Prc_RIS_ORDERIMAGES_Update,
        Prc_RIS_CLINICSESSION_Select,

        Prc_RIS_SCHEDULE_Session,
        Prc_RIS_SCHEDULE_SelectModality,
        Prc_RIS_SCHEDULE_SessionTime,
        Prc_RIS_SCHEDULE_SelectHN,

        Prc_RIS_EXAMRESULTTEMPLATELOG_Select,
        Prc_RIS_EXAMLOG_Select,
        Prc_GBL_ENVLOG_Select,
        Prc_RIS_SCHEDULELOG_Select2,

        Prc_HR_EMP_Delete,
        Prc_HR_EMP_Insert,
        Prc_HR_EMP_Select,
        Prc_HR_EMP_Update,

        GBLLanguage_Select2,

        Prc_RIS_Rpt_BiopsyResult,
        Prc_RIS_SEARCH_Select1,
        Prc_RIS_SEARCH_Select2,
        Prc_RIS_SEARCH_Select3,

        Prc_RIS_SCHEDULE_LOG_Select,

        Prc_RIS_SCHEDULE_SelectMultiPrint,
        Prc_GBL_Favourite_Select,
        Prc_RIS_Rpt_OrderReportAll,

        Prc_RIS_ORDERDTL_SelectByCapture_withHN,

        //------------------Employee schedule
        GBLEmpSchedule_Select,
        GBLEmpSchedule_Insert,
        GBLEmpSchedule_Delete,
        GBLEmpSchedule_Update,
        Prc_LookUp_Result_Select,



        //Inventory
        Prc_INV_PR_SelectAll,
        Prc_INV_PO_SelectAll,
        Prc_INV_REQUISITION_SelectAll,
        Prc_LookUp_INV_PR_SelectForPO,



        Prc_RIS_ORDER_SelectByXrayNumber,
        Prc_HR_ROOM_Select,


        //New Schedule
        Prc_RIS_SCHEDULE_CheckFree,

        Prc_XREGIST_WorkList,
        Prc_XREGIST_GetRequest,
        Prc_XREGIST_Status,
        Prc_XREGIST_GetByHN,
        XREGIST_ExamInsert,
        Prc_XREGIST_SelectByDate,
        Prc_XREGIST_SelectByID,
        Prc_XREGIST_SelectByHN,
        Prc_XREGIST_GetSREQ,

        Prc_RIS_EXAMRESULTRADS_Select,

        Prc_GBL_SUBMENU_Select,
        Prc_GBL_ROLE_Insert,

        Prc_RIS_ORDER_CancelTemplate,
        Prc_RIS_ORDER_Select_frmOrderIsCancel,
        Prc_RIS_ORDER_CancelwithReason,

        Prc_RIS_EXAM_Update_Barcode,
        Prc_RIS_EXAM_Select_NonInterventConsumable,
        Prc_RIS_EXAM_Select_ByBarcode,
        Prc_RIS_EXAM_Select_Intervent,

        Prc_HIS_REGISTRATION_SelectAll,
        Prc_HIS_REGISTRATION_Select_LastRecord,

        Prc_RIS_MODALITYMAINTENANCETYPE_Select,
        Prc_RIS_MODALITYMAINTENANCETYPE_Insert,
        Prc_RIS_MODALITYMAINTENANCETYPE_Update,
        Prc_RIS_MODALITYMAINTENANCETYPE_Delete,

        Prc_RIS_Rpt_ModalityMaintenanceSchedule,
        Prc_RIS_MODALITYMAINTENANCESCHEDULE_Select_Worklist,
        Prc_RIS_MODALITYMAINTENANCESCHEDULE_Select_Schedule,
        Prc_RIS_MODALITYMAINTENANCESCHEDULE_Update,
        Prc_RIS_MODALITYMAINTENANCESCHEDULE_ChangeStatus,
        Prc_RIS_MODALITYMAINTENANCESCHEDULE_Insert,
        Prc_RIS_MODALITYMAINTENANCESCHEDULE_Delete,

        Prc_RIS_SCHEDULEDTL_Insert,
        Prc_RIS_SCHEDULEDTL_Delete,
        Prc_RIS_EXAMPANEL_Select,

        Prc_RIS_SCHEDULE_UpdateModality,
        Prc_XREGIST_GetByREQ,
        Prc_RIS_EXAM_SelectAll_IncludeUnActive,
        Prc_XREGIST_GetByREQDate,

        Prc_RIS_EXAMRESULTKEYIMAGES_Select,
        Prc_RIS_EXAMRESULTKEYIMAGES_Insert,
        Prc_RIS_EXAMRESULTKEYIMAGES_Delete,
        Prc_RIS_EXAMRESULTKEYIMAGES_Update,

        Prc_LookUp_ClinicalData_Select,
        Prc_RIS_BillingGenMessage,
        Prc_RIS_ORDER_UpdateEncounter,

        Prc_RIS_SCHEDULE_InsertRecurrence,
        Prc_RIS_SCHEDULE_UpdateRecurrence,

        Prc_FIN_PAYMENTDTL_UpdateStatus,

        Prc_RIS_BILLINGTRANSACTIONLOG_Insert,
        Prc_RIS_BILLINGTRANSACTIONLOGDTL_Insert,
        Prc_RIS_ORDER_Reprint_1,

        Prc_RIS_ORDER_Update_ADMISSION_NO,
        Prc_RIS_SCHEDULE_UpdatePatientStatus,
        GBL_Sequences_SelectRunNo_OnlineArrivalWorklist,

        Prc_GBL_MESSAGE_SelectByMsgID,
        Prc_GBL_MESSAGE_SelectByStatus,
        Prc_GBL_MESSAGE_Select_Trash,
        Prc_GBL_MESSAGE_Update,
        Prc_GBL_MESSAGE_Update_Star,
        Prc_GBL_MESSAGE_Update_Trash,
        Prc_GBL_MESSAGERECIPIENT_Select,
        Prc_GBL_MESSAGERECIPIENT_SelectByMsgID,
        Prc_GBL_MESSAGE_Insert,
        Prc_GBL_MESSAGERECIPIENT_Insert_Send,
        Prc_GBL_MESSAGERECIPIENT_Update_Read,
        Prc_GBL_MESSAGERECIPIENT_Update_Star,
        Prc_GBL_MESSAGERECIPIENT_Update_Trash,
        Prc_HR_EMP_SelectLite,
        Prc_RIS_ORDERDTL_UpdateHL7Flag,
        Prc_RIS_RELEASEMEDIA_SelectNew,
        Prc_WS_Insert,
        Prc_XREGIST_SelectByDateTime,
        Prc_RIS_ORDER_ReprintStickerQSHC,
        Prc_RIS_ORDER_ReprintStickerQSHCByOrdID,
        Prc_RIS_MATCHING_SELECT,
        Prc_XREGIST_Update,
        Prc_RIS_PATIENTDESTINATION_Select,
        Prc_RIS_CLINICALINDICATION_Select,
        Prc_RIS_CLINICALINDICATIONTYPE_Select,
        Prc_RIS_SCHEDULE_CheckFreeSlot,
        Prc_RIS_SCHEDULE_Busy,
        Prc_RIS_SCHEDULE_WaitingList,
        Prc_RIS_SCHEDULE_UpdateNotifyAdmin,
        Prc_RIS_SCHEDULE_AppointmentCount,
        Prc_RIS_SCHEDULE_SelectTest,

        #region Envision Online
        Prc_RIS_CLINICALINDICATION_Select2,
        Prc_RIS_CLINICALINDICATIONTYPE_Select2,
        Prc_RIS_ORDERCLINICALINDICATION_Insert2,

        Prc_ONL_Worklist_Select,
        Prc_RIS_MODALITYTYPE_SelectOnline,

        Prc_RIS_MODALITYEXAMTop10_SelectByModolity,
        Prc_RIS_MODALITYEXAMFAVORITE_SelectByModolity,
        Prc_RIS_EXAMFAVORITE_Delete,
        Prc_RIS_EXAMFAVORITE_Insert,

        Prc_RIS_CLINICALINDICATIONTYPEFAVORITES_Select,
        Prc_RIS_CLINICALINDICATIONTYPEFAVORITE_DELETE,
        Prc_RIS_CLINICALINDICATIONTYPEFAVORITE_INSERT,

        Prc_RIS_CLINICALINDICATIONFAVORITES_Select,
        Prc_RIS_CLINICALINDICATIONFAVORITES_Delete,
        Prc_RIS_CLINICALINDICATIONFAVORITES_Insert,

        Prc_ONLXrayreq_Delete,
        Prc_ONLXrayreqdtl_Delete,
        Prc_XRAYREQDTL_Insert,
        Prc_XRAYREQDTL_Update,
        Prc_XRAYREQ_Insert,
        Prc_XRAYREQ_Update,

        Prc_RIS_SCHEDULE_InsertOnline,
        Prc_RIS_EXAM_Select2,
        Prc_HR_EMP_ByEmpUID_PWD_Select,

        Prc_ONL_CONFLICTEXAM_Select,

        Prc_RIS_SESSIONMAXAPP_Select,
        Prc_RIS_SESSIONTIME_Select,
        Prc_RIS_SESSIONTIMEONLINE_Select,
        Prc_RIS_SCHEDULE_COUNTINSESSIONTIME_Select,
        Prc_RIS_SESSIONTIMEUNIT_Select,

        Prc_RIS_EXAMPANELPORTABLE_Select,
        Prc_RIS_EXAMPANELPORTABLE_SelectAll,
        Prc_RIS_ORDERCLINICALINDICATION_Insert,
        Prc_RIS_CLINICALINDICATION_Delete,
        Prc_RIS_CLINICALINDICATION_Select_CIID,
        Prc_RIS_CLINICALINDICATION_Insert,
        Prc_RIS_CLINICALINDICATIONTYPE_Select_CIID,
        Prc_RIS_CLINICALINDICATIONTYPE_Insert,
        Prc_RIS_CLINICALINDICATIONTYPE_Delete,

        Prc_RIS_ORDERICD_Insert,
        Prc_RIS_ORDER_SelectOrderReport,
        Prc_XRAYREQ_SelectOrderReport,

        Prc_RIS_SCHEDULE_Online_Insert,
        Prc_RIS_SCHEDULE_Online_Update,
        Prc_RIS_ORDER_ReportBillingOnline,
        Prc_RIS_EXAM_SelectAll2,
        Prc_ONL_CLINICSESSION_Select,

        Prc_RIS_CLINICSESSION_SelectByAppointDate,
        Prc_RIS_MODALITYEXAM_SelectIDByPatDestID,
        Prc_RIS_SCHEDULE_Delete,
        Prc_ONLHR_UNIT_Select,
        Prc_Patient_Registration_PhoneUpdate,
        Prc_RIS_EXAM_SelectOnline,
        Prc_RIS_MODALITYEXAM_SelectByModolityType,
        
        Prc_RIS_ORDERCLINICALINDICATIONTYPE_Insert2,
        Prc_RIS_ORDERCLINICALINDICATION_ONL_Select,
        Prc_RIS_ORDERCLINICALINDICATIONTYPE_ONL_Select,
        Prc_RIS_ORDERCLINICALINDICATION_Delete,
        Prc_RIS_ORDERCLINICALINDICATIONTYPE_Delete2,

        Prc_ONL_Worklist_Select_test,
        Prc_RIS_SESSIONTIMEONLINE_CHILDREN_Select,
        Prc_RIS_SESSIONTIMEONLINE_SelectAll,
        Prc_RIS_SCHEDULE_CHECKBLOCK_Select,
        Prc_RIS_SCHEDULE_Online_Select,
        Prc_RIS_EXAMFAVORITE_UPDATE,
        Prc_LookUp_PatientDestination_Select,
        Prc_RIS_EXAM_SelectOnlineAll,
        Prc_ONL_SearchMatch_Select,

        Prc_RIS_SCHEDULE_XRPTNAV,
        Prc_RIS_EXAMINSTRUCTIONS_SelectNavigation,
        Prc_HR_EMP_UpdateRole,
        Prc_RIS_SCHEDULE_CheckPatientDistination,
        Prc_RIS_SESSIONTIMEUNIT_SelectChildren,
        Prc_RIS_SESSIONTIMEUNIT_Select2,

        Prc_ONL_Worklist_Select_SCHEUDLE,
        Prc_ONL_Worklist_Select_ORDER,
        Prc_ONL_Worklist_Select_XRAY,
        Prc_ONL_HISLINKLOG_Insert,

        Prc_RIS_PATSTATUS_SelectActive,
        Prc_ONL_RepairDataOnline,
        Prc_RIS_CLINICALINDICATIONWITHUNIT_Select,
        Prc_RIS_CLINICALINDICATIONWITHUNIT_Insert,
        Prc_RIS_CLINICALINDICATIONWITHUNIT_Delete,
        Prc_RIS_CLINICALINDICATIONWITHUNIT_DeleteAll,
        #endregion


        Prc_GBL_ERRORLOGS_Select,
        Prc_GBL_ERRORLOGS_SelectByUserId,
        Prc_GBL_ERRORLOGS_SelectByIP,
        Prc_GBL_ERRORLOGS_SelectByDate,
    }
}

