//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;
namespace Envision.WebService.EMROERWebService
{
    // 
    // This source code was auto-generated by wsdl, Version=2.0.50727.3038.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "ServiceSoap", Namespace = "http://tempuri.org/")]
    public partial class EMROERWebService : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback GetEMRbyMRNOperationCompleted;

        /// <remarks/>
        public EMROERWebService()
        {
            this.Url = "http://miracle99/EMROERWebservice/Service.asmx";
        }

        /// <remarks/>
        public event GetEMRbyMRNCompletedEventHandler GetEMRbyMRNCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetEMRbyMRN", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetEMRbyMRN(string MRN)
        {
            object[] results = this.Invoke("GetEMRbyMRN", new object[] {
                    MRN});
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetEMRbyMRN(string MRN, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetEMRbyMRN", new object[] {
                    MRN}, callback, asyncState);
        }

        /// <remarks/>
        public System.Data.DataSet EndGetEMRbyMRN(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public void GetEMRbyMRNAsync(string MRN)
        {
            this.GetEMRbyMRNAsync(MRN, null);
        }

        /// <remarks/>
        public void GetEMRbyMRNAsync(string MRN, object userState)
        {
            if ((this.GetEMRbyMRNOperationCompleted == null))
            {
                this.GetEMRbyMRNOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEMRbyMRNOperationCompleted);
            }
            this.InvokeAsync("GetEMRbyMRN", new object[] {
                    MRN}, this.GetEMRbyMRNOperationCompleted, userState);
        }

        private void OnGetEMRbyMRNOperationCompleted(object arg)
        {
            if ((this.GetEMRbyMRNCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEMRbyMRNCompleted(this, new GetEMRbyMRNCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void GetEMRbyMRNCompletedEventHandler(object sender, GetEMRbyMRNCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEMRbyMRNCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetEMRbyMRNCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public System.Data.DataSet Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}